import type { SchemaIR, SqlDialect, TableIR } from "../ir/types.js";
import type { Dataset, RowValue } from "../engine/types.js";

export interface SqlRenderOptions {
  dialect?: SqlDialect;
  /** Metadata to include in the header comment. */
  metadata?: Record<string, string | number | undefined>;
}

/**
 * Render a Dataset to a runnable `.sql` file. Statements are grouped by table
 * in the supplied topological order, wrapped in a transaction, and prefixed
 * with a commented-out TRUNCATE block the user can opt into.
 */
export function renderSql(
  ir: SchemaIR,
  orderedTables: TableIR[],
  dataset: Dataset,
  options: SqlRenderOptions = {},
): string {
  const dialect = options.dialect ?? ir.dialect ?? "postgresql";
  const out: string[] = [];

  out.push(headerComment(options.metadata));
  out.push("");
  out.push("-- Optional reset (uncomment if you want a clean slate before seeding):");
  for (let i = orderedTables.length - 1; i >= 0; i--) {
    out.push(`-- DELETE FROM ${quoteIdent(orderedTables[i]!.name, dialect)};`);
  }
  out.push("");
  out.push("BEGIN;");
  out.push("");

  for (const table of orderedTables) {
    const rows = dataset.get(table.name) ?? [];
    if (rows.length === 0) continue;
    const cols = table.columns.filter((c) => !c.isGenerated).map((c) => c.name);
    out.push(`-- ${table.name}: ${rows.length} row${rows.length === 1 ? "" : "s"}`);
    out.push(
      `INSERT INTO ${quoteIdent(table.name, dialect)} (${cols
        .map((c) => quoteIdent(c, dialect))
        .join(", ")}) VALUES`,
    );
    const valueLines = rows.map((row, i) => {
      const tuple = cols.map((c) => quoteValue(row[c] ?? null, dialect)).join(", ");
      const sep = i === rows.length - 1 ? ";" : ",";
      return `  (${tuple})${sep}`;
    });
    out.push(...valueLines);
    out.push("");
  }

  out.push("COMMIT;");
  out.push("");
  return out.join("\n");
}

function headerComment(metadata?: Record<string, string | number | undefined>): string {
  // No timestamps in the file header — byte-identical output for the same seed (PRD §16.6).
  const lines = ["-- Generated by auto-seed"];
  if (metadata) {
    for (const [k, v] of Object.entries(metadata)) {
      if (v !== undefined) lines.push(`-- ${k}: ${v}`);
    }
  }
  return lines.join("\n");
}

function quoteIdent(name: string, dialect: SqlDialect): string {
  if (dialect === "mysql") return "`" + name.replace(/`/g, "``") + "`";
  // Postgres + SQLite: double-quote (safe for mixed-case identifiers too)
  return '"' + name.replace(/"/g, '""') + '"';
}

function quoteValue(v: RowValue, dialect: SqlDialect): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") {
    if (dialect === "sqlite" || dialect === "mysql") return v ? "1" : "0";
    return v ? "TRUE" : "FALSE";
  }
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return "NULL";
    return String(v);
  }
  if (typeof v === "bigint") return String(v);
  if (v instanceof Date) return `'${formatSqlDatetime(v)}'`;
  if (Array.isArray(v)) {
    // Postgres array literal: '{a,b}'. Empty array → '{}'.
    const elems = v.map((e) => String(e).replace(/(["\\])/g, "\\$1"));
    return `'{${elems.join(",")}}'`;
  }
  if (typeof v === "object") return `'${escapeSqlString(JSON.stringify(v), dialect)}'`;
  // string
  return `'${escapeSqlString(String(v), dialect)}'`;
}

function formatSqlDatetime(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())} ${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}`;
}

function escapeSqlString(s: string, _dialect: SqlDialect): string {
  // Universal SQL string escaping: double the single quote.
  return s.replace(/'/g, "''");
}
