import type { SchemaIR, TableIR } from "../ir/types.js";
import type { Dataset, RowValue } from "../engine/types.js";

export interface TsRenderOptions {
  metadata?: Record<string, string | number | undefined>;
}

export function renderTypeScript(
  ir: SchemaIR,
  orderedTables: TableIR[],
  dataset: Dataset,
  options: TsRenderOptions = {},
): string {
  switch (ir.source) {
    case "prisma":
      return renderPrisma(ir, orderedTables, dataset, options);
    case "typeorm":
      return renderTypeOrm(ir, orderedTables, dataset, options);
    case "sql":
    default:
      return renderPlain(ir, orderedTables, dataset, options);
  }
}

function header(metadata?: Record<string, string | number | undefined>): string {
  // No timestamps in the file header — byte-identical output for the same seed (PRD §16.6).
  const lines = ["// Generated by auto-seed"];
  if (metadata) {
    for (const [k, v] of Object.entries(metadata)) {
      if (v !== undefined) lines.push(`// ${k}: ${v}`);
    }
  }
  return lines.join("\n");
}

function literal(v: RowValue): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return "null";
    return String(v);
  }
  if (typeof v === "bigint") return `${v}n`;
  if (v instanceof Date) return `new Date(${JSON.stringify(v.toISOString())})`;
  if (Array.isArray(v)) return JSON.stringify(v);
  if (typeof v === "object") return JSON.stringify(v);
  return JSON.stringify(String(v));
}

function rowObject(row: Record<string, RowValue>, cols: string[]): string {
  const entries = cols.map((c) => `${safeKey(c)}: ${literal(row[c] ?? null)}`);
  return `{ ${entries.join(", ")} }`;
}

function safeKey(name: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) return name;
  return JSON.stringify(name);
}

function renderPrisma(
  _ir: SchemaIR,
  ordered: TableIR[],
  dataset: Dataset,
  opts: TsRenderOptions,
): string {
  const lines: string[] = [];
  lines.push(header(opts.metadata));
  lines.push("import { PrismaClient } from '@prisma/client';");
  lines.push("");
  lines.push("const prisma = new PrismaClient();");
  lines.push("");
  lines.push("async function main() {");
  for (const t of ordered) {
    const rows = dataset.get(t.name) ?? [];
    if (rows.length === 0) continue;
    const cols = t.columns.filter((c) => !c.isGenerated).map((c) => c.name);
    const accessor = lowerFirst(t.name);
    lines.push(`  await prisma.${accessor}.createMany({`);
    lines.push(`    data: [`);
    for (const row of rows) {
      lines.push(`      ${rowObject(row, cols)},`);
    }
    lines.push(`    ],`);
    lines.push(`    skipDuplicates: true,`);
    lines.push(`  });`);
  }
  lines.push("}");
  lines.push("");
  lines.push("main()");
  lines.push("  .catch((e) => {");
  lines.push("    console.error(e);");
  lines.push("    process.exit(1);");
  lines.push("  })");
  lines.push("  .finally(async () => {");
  lines.push("    await prisma.$disconnect();");
  lines.push("  });");
  lines.push("");
  return lines.join("\n");
}

function renderTypeOrm(
  _ir: SchemaIR,
  ordered: TableIR[],
  dataset: Dataset,
  opts: TsRenderOptions,
): string {
  const lines: string[] = [];
  lines.push(header(opts.metadata));
  lines.push("// Adjust the import path to wherever your DataSource is defined.");
  lines.push("import { AppDataSource } from './data-source';");
  lines.push("");
  lines.push("async function main() {");
  lines.push("  await AppDataSource.initialize();");
  for (const t of ordered) {
    const rows = dataset.get(t.name) ?? [];
    if (rows.length === 0) continue;
    const cols = t.columns.filter((c) => !c.isGenerated).map((c) => c.name);
    lines.push(`  await AppDataSource.createQueryBuilder()`);
    lines.push(`    .insert()`);
    lines.push(`    .into(${JSON.stringify(t.name)})`);
    lines.push(`    .values([`);
    for (const row of rows) {
      lines.push(`      ${rowObject(row, cols)},`);
    }
    lines.push(`    ])`);
    lines.push(`    .execute();`);
  }
  lines.push("  await AppDataSource.destroy();");
  lines.push("}");
  lines.push("");
  lines.push("main().catch((e) => { console.error(e); process.exit(1); });");
  lines.push("");
  return lines.join("\n");
}

function renderPlain(
  _ir: SchemaIR,
  ordered: TableIR[],
  dataset: Dataset,
  opts: TsRenderOptions,
): string {
  const lines: string[] = [];
  lines.push(header(opts.metadata));
  lines.push("// No ORM was inferred; this file exports a typed dataset you can load yourself.");
  lines.push("");
  lines.push("export const seedData = {");
  for (const t of ordered) {
    const rows = dataset.get(t.name) ?? [];
    const cols = t.columns.filter((c) => !c.isGenerated).map((c) => c.name);
    lines.push(`  ${safeKey(t.name)}: [`);
    for (const row of rows) {
      lines.push(`    ${rowObject(row, cols)},`);
    }
    lines.push(`  ],`);
  }
  lines.push("} as const;");
  lines.push("");
  return lines.join("\n");
}

function lowerFirst(s: string): string {
  return s.length === 0 ? s : s[0]!.toLowerCase() + s.slice(1);
}
