-- Generated by auto-seed
-- tool: auto-seed
-- model: openai/gpt-4o-mini
-- seed: 1966345368
-- rows: 120
-- tables: 12

-- Optional reset (uncomment if you want a clean slate before seeding):
-- DELETE FROM `wp_usermeta`;
-- DELETE FROM `wp_postmeta`;
-- DELETE FROM `wp_commentmeta`;
-- DELETE FROM `wp_comments`;
-- DELETE FROM `wp_posts`;
-- DELETE FROM `wp_users`;
-- DELETE FROM `wp_termmeta`;
-- DELETE FROM `wp_term_relationships`;
-- DELETE FROM `wp_term_taxonomy`;
-- DELETE FROM `wp_terms`;
-- DELETE FROM `wp_options`;
-- DELETE FROM `wp_links`;

BEGIN;

-- wp_links: 10 rows
INSERT INTO `wp_links` (`link_id`, `link_url`, `link_name`, `link_image`, `link_target`, `link_description`, `link_visible`, `link_owner`, `link_rating`, `link_updated`, `link_rel`, `link_notes`, `link_rss`) VALUES
  (1, 'https://genuine-makeover.info', 'caelum', 'https://picsum.photos/seed/E3GMf/509/260', 'conscendo', 'Valeo amplus tametsi commodo utrum.', 'no', 1, 5819787517917072, '2025-12-31T20:23:20.751Z', 'adversus', 'Audacia atrocitas thorax adinventitias artificiose sordeo umerus defendo.', 'https://slow-larva.name/'),
  (2, 'https://orange-molasses.org', 'charisma', 'https://picsum.photos/seed/cCWcjCk49b/3427/1813', 'demens', 'Spectaculum sui sint concido nesciunt colo.', 'no', 2, 267822141019579, '2025-12-31T11:38:06.635Z', 'abutor', 'Compello ulterius advenio curso doloremque.', 'https://questionable-catalyst.info/'),
  (3, 'https://firm-circumference.com/', 'corrigo', 'https://picsum.photos/seed/moX9Wb/808/459', 'quasi', 'Est magnam ipsam.', 'yes', 3, 1936472844889659, '2025-12-31T22:21:35.553Z', 'cribro', 'Brevis vomer brevis sit crux thermae candidus taedium.', 'https://total-confusion.com'),
  (4, 'https://impeccable-fold.name', 'quibusdam', 'https://picsum.photos/seed/yK7ag7U8/481/2001', 'via', 'Aufero carmen consequuntur ullus depereo agnitio.', 'yes', 4, 3028899061492832, '2025-12-31T05:21:16.917Z', 'terga', 'Defluo alter atrox sodalitas nobis vigilo tamen stella sufficio sui.', 'https://shady-membership.com'),
  (5, 'https://frequent-hunt.name', 'tunc', 'https://picsum.photos/seed/5Vr2IZ/3898/548', 'bestia', 'Aduro sulum conor ars maxime adimpleo voluptatibus crinis sollers confero.', 'yes', 5, 2767059690521227, '2025-12-31T05:56:41.107Z', 'curto', 'Admoneo tendo soluta angulus reprehenderit ustilo acer vos suscipio antepono.', 'https://ecstatic-slide.com'),
  (6, 'https://internal-handful.name', 'quasi', 'https://picsum.photos/seed/4rlk6zvr3W/2302/3375', 'arceo', 'Virga acer cribro curiositas supplanto.', 'no', 6, 2657389602938949, '2025-12-31T23:47:42.674Z', 'causa', 'Maiores quae voluptate vicissitudo.', 'https://tired-reasoning.biz'),
  (7, 'https://considerate-window.info/', 'arguo', 'https://picsum.photos/seed/87djV04n/2029/676', 'traho', 'Blandior vito tener degero arca vesper.', 'yes', 7, 611698850367159, '2025-12-31T19:07:01.900Z', 'uredo', 'Odio cometes ullus vis.', 'https://untried-ravioli.org/'),
  (8, 'https://lawful-pecan.org/', 'sortitus', 'https://picsum.photos/seed/uUztV/127/2578', 'temeritas', 'Armarium deorsum autus aspicio alter caelum amicitia demitto uter tamdiu.', 'yes', 8, 6757990596859863, '2025-12-31T01:47:17.758Z', 'placeat', 'Cupio solvo auditor ipsam.', 'https://muffled-digestive.org'),
  (9, 'https://questionable-phrase.info/', 'subiungo', 'https://picsum.photos/seed/O32u7/1539/1868', 'balbus', 'Depereo caute comminor calcar virgo aureus.', 'yes', 9, 91678229493980, '2025-12-31T01:13:50.570Z', 'harum', 'Vinco sufficio conor assentator utor verus correptius creber.', 'https://untried-tomb.net/'),
  (10, 'https://known-going.org/', 'tabula', 'https://picsum.photos/seed/PkelDhnC/3562/2873', 'custodia', 'Coerceo laborum desino.', 'yes', 10, 4540604771897933, '2025-12-31T14:37:13.934Z', 'averto', 'Non maiores excepturi.', 'https://juicy-disadvantage.com');

-- wp_options: 10 rows
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
  (1, 'admiratio', 'Ultio adeo stultus compello calamitas amissio tolero tredecim.', 'no'),
  (2, 'iusto', 'Anser eaque taceo illo aer laudantium comprehendo vaco nesciunt correptius.', 'yes'),
  (3, 'voluptas', 'Congregatio valens absens iure temperantia ad speculum.', 'no'),
  (4, 'collum', 'Delectus cognomen derelinquo tamen.', 'yes'),
  (5, 'eaque', 'Avarus cubicularis trado sumptus vergo atrox cresco concido porro.', 'yes'),
  (6, 'volubilis', 'Cupressus harum subito.', 'no'),
  (7, 'cernuus', 'Coaegresco contra repudiandae conculco via viduo adflicto ultio adfero.', 'no'),
  (8, 'una', 'Advenio canis curia cunctatio.', 'yes'),
  (9, 'depraedor', 'Suscipio copia correptius.', 'no'),
  (10, 'patrocinor', 'Adipisci tollo aestivus caterva odio bis cohors cupiditas sordeo dedico.', 'no');

-- wp_terms: 10 rows
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
  (1, 'quibusdam', 'sunt-cibo-testimonium', 6448224727786346),
  (2, 'theca', 'bene-deleo-asporto', 4846682878502050),
  (3, 'comminor', 'corrupti-vulticulus-valde', 7328237217546994),
  (4, 'capio', 'sustineo-approbo-auditor', 8199322593987934),
  (5, 'aliquid', 'a-amor-ab', 1249687992956372),
  (6, 'termes', 'concedo-charisma-peccatus', 87623163318199),
  (7, 'sursum', 'cilicium-tersus-ustulo', 3174204005102576),
  (8, 'titulus', 'demonstro-tabella-uredo', 770898200582052),
  (9, 'deorsum', 'conor-vivo-testimonium', 3752306913981116),
  (10, 'venio', 'uxor-aegrotatio-vallum', 3101685612653239);

-- wp_term_taxonomy: 10 rows
INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
  (1, 2, 'vulgaris', 'Ad termes nam.', 1, 6152963693076538),
  (2, 9, 'adversus', 'Pecco avaritia tracto vae subito ancilla vulgivagus velit aer.', 1, 4191151388234893),
  (3, 9, 'alii', 'Vicinus comis aliquid provident.', 1, 2137455407469137),
  (4, 10, 'aegrus', 'Dedico valens cariosus commodi cunabula tepidus audax.', 1, 6824592253867186),
  (5, 9, 'blandior', 'Acervus acidus suggero patrocinor somniculosus.', 1, 6019945600841155),
  (6, 2, 'earum', 'Voco harum commodi placeat coniuratio audax deficio.', 1, 4753476274724186),
  (7, 9, 'viduo', 'Subseco consequatur carbo depraedor.', 1, 8076844136716881),
  (8, 2, 'balbus', 'Adeo contego coniecto compello vespillo aequus suadeo.', 1, 2596598883523705),
  (9, 7, 'calcar', 'Tersus umerus tonsor arto summisse.', 1, 6212131509725208),
  (10, 1, 'demens', 'Depono tot impedit vitae decor tergo decens ventito cruciamentum.', 1, 5259261965869959);

-- wp_term_relationships: 10 rows
INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
  (1, 2, 1644355525290578),
  (2, 10, 6224292400159776),
  (3, 8, 3565888238129979),
  (4, 2, 1442661013510828),
  (5, 5, 3585183375216341),
  (6, 2, 1831699653737947),
  (7, 10, 882517028816431),
  (8, 6, 7402125504353254),
  (9, 2, 3289377476439439),
  (10, 5, 5855838917762736);

-- wp_termmeta: 10 rows
INSERT INTO `wp_termmeta` (`meta_id`, `term_id`, `meta_key`, `meta_value`) VALUES
  (1, 5, 'ab', NULL),
  (2, 4, 'degusto', 'At vinum adduco taceo impedit veritatis cunabula crur theologus virgo.'),
  (3, 7, 'aranea', 'Tamisium carcer textilis laudantium.'),
  (4, 4, 'demonstro', NULL),
  (5, 9, 'aro', 'Aestas antiquus vivo arma adnuo ago.'),
  (6, 3, 'libero', 'Deleo ambulo pectus tracto vesper advenio.'),
  (7, 3, 'pecco', NULL),
  (8, 2, 'nostrum', 'Ulterius decerno accedo denuncio vallum paens depraedor bis.'),
  (9, 8, 'vallum', NULL),
  (10, 10, 'talio', NULL);

-- wp_users: 10 rows
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
  (1, 'Myrtie_Konopelski', 'bZLVefB3ZIt2Xcc', 'Ervin', 'Dan.Kuvalis45@yahoo.com', 'https://trusting-fen.name', '2025-12-23T04:07:37.260Z', 'w6voVxRSvp08dOUzH7Uxjk7aLMwtFkrWakQJTkUfHI3gcMJQMitAouFBlFgl7hVJ', 1, 'Betty Gleichner'),
  (2, 'Jamarcus.Murazik-Cronin74', 'E4y6ZvuLalAGP0p', 'Harriet', 'Jackie78@hotmail.com', 'https://left-lamp.biz/', '2025-01-18T23:08:42.922Z', 'KuW6MRowbFblvlpARIBqOlZ4LybfTO8a5NGpYbUHzR0JLnxaw2BYHrxfiJdGioU8', 1, 'Greg Schuppe III'),
  (3, 'Adriana_Emard', 'ofSADffsh3eWYVw', 'Jennifer', 'Joanna_Connelly@yahoo.com', 'https://honorable-remark.name', '2025-08-20T03:08:43.291Z', '4mlPDbL4uIjxZzpeVgNtpmxxbZMnaQPG6ilSxCLfiT2YiAIQwVDjKhhuQ8MdCTpJ', 0, 'Okey Collier'),
  (4, 'Naomi.Haag', 'TL_7FKlzBjXHVtb', 'Mckenzie', 'Monica57@yahoo.com', 'https://feline-submitter.name/', '2025-09-25T05:09:10.470Z', 'hfjqUjLXnvwqWqUiHkikmO21GFv4ESTdqVZ4b7E1lKB3UcHlEyCW8OZfFwwDhrew', 4, 'Presley Thompson'),
  (5, 'Luz.Lebsack-Barrows0', '2YeaCrQH3xvEUur', 'Luz', 'Anne_Gutmann23@yahoo.com', 'https://new-solution.name/', '2025-01-19T05:30:42.899Z', 'nlr6bPWH3AkQr8DpIIMRjvudUsGNJZUWJexP7d82fVYoJrsiakWV3VYLfcAaLxIk', 5, 'Dillan Sporer'),
  (6, 'Harvey.Lindgren', 'PQc0qrIQA_NCVNt', 'Rosa', 'Marta.Bartell64@hotmail.com', 'https://stingy-perfection.com/', '2025-07-21T09:06:09.698Z', 'KRtbvPMZVkecpGsUVdMI1MW4VWl594snDXoE1eTwp1zrut0regVaduLRJh5XSC3m', 4, 'Luna West'),
  (7, 'Garrison_Trantow43', 'TdS8ArnzYUUsw3_', 'Zachery', 'Walter94@gmail.com', 'https://darling-birdcage.org', '2025-02-01T03:16:32.543Z', 'Lb6uxjWfcb9LQ2pOMY0XmhipFhYyVcnC0PvT1iCSI5cG6WWZ80WTOJAJR58c2ij9', 4, 'Alysha Conn'),
  (8, 'General33', 'eLbD5EYqnEQ_Fak', 'Bobbie', 'Bonnie_Schmeler29@gmail.com', 'https://alarmed-marathon.name/', '2025-01-19T09:24:44.167Z', '4YlIEHRUSItRruOud8aAdiIug3dDIfV5ifgc1TrEKHgh1m9MJkz1TJlcEJamfP7R', 4, 'Jeannie Rogahn'),
  (9, 'Jovani_Schmidt', '1OBlabyidtN_DTw', 'Grayce', 'Jerry_Hayes13@gmail.com', 'https://tragic-perfection.biz', '2025-05-05T03:09:39.389Z', 'Zz9OI5gxJbKU6tqzdE9lKa6VTJbhJfsItlnSHsCA3lPHXoPtgy8Mi2bTrGvPaaGl', 5, 'Ervin Torphy'),
  (10, 'Ron_Ratke', 'gaBUuMz5_tFbepa', 'Viviane', 'Carole_Bogan@hotmail.com', 'https://impure-hope.name', '2025-01-04T09:43:39.699Z', 'NiPQbvxuxcqk0sXXy5ccYnBdN0RSokO5qoDbAWwztY7iTL40YD0FL0I4F2Lr8P8B', 2, 'Ebony Boehm');

-- wp_posts: 10 rows
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
  (1, 7, '2025-07-23T19:18:05.925Z', '2025-08-17T22:51:22.463Z', 'Cras absens thalassinus solium careo aestus impedit. Coerceo cruciamentum virtus peior tertius sufficio. Auctor cernuus dolore defero amitto demoror spoliatio aiunt necessitatibus.', 'Tredecim beatae dedecor tum.', 'Suadeo uredo vulgivagus cado ad crepusculum.', 'publish', 'open', 'open', 'QSr89nbENEYE9YuH', 'crapula-laborum-arbor', 'https://lavish-populist.biz/', 'https://outlying-blowgun.com/', '2025-12-31T21:40:58.120Z', '2025-12-31T21:20:34.908Z', 'Sulum tredecim admitto quas tenetur. Thorax utor clibanus synagoga amplitudo pariatur arca astrum triumphus. Creo caste incidunt aestus curto beneficium ex ultio alienus stipes.', 1, 'https://polite-hunt.com/', 3, 'post', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 957968892267083),
  (2, 6, '2025-11-11T01:41:11.375Z', '2025-01-17T19:08:16.166Z', 'Sto ciminatio sophismata tubineus demens decipio temporibus. Crur peccatus canonicus caveo sustineo delibero. Vere aperio amiculum anser et.', 'Tribuo supra cohibeo suppellex bardus laudantium sequi iste admiratio conscendo.', 'Desino commemoro decor voluptatum.', 'publish', 'open', 'open', 'yjdXdgUKsGbeLwVE', 'contego-demonstro-administratio', 'https://memorable-window.com', 'https://probable-puritan.biz', '2025-12-31T14:50:32.643Z', '2025-12-31T05:38:16.075Z', 'Alii dolor agnosco deporto capitulus damno artificiose curvo. Triduana combibo assentator patrocinor acceptus. Ullus substantia similique conforto.', 1, 'https://definite-charlatan.info/', 1, 'post', 'image/png', 8860071953485187),
  (3, 1, '2025-12-28T17:06:44.962Z', '2025-08-15T19:58:53.676Z', 'Hic virtus colo nesciunt cunae adipiscor suppellex saepe audio clibanus. Adsidue torqueo utilis tabesco bene demitto. Vomito vita tantum est asperiores angelus unde cibo vinculum tantillus.', 'Ciminatio vorago depraedor optio uter concedo triumphus.', 'Valetudo nesciunt thermae ascisco concido fugiat attollo vestigium compello.', 'publish', 'open', 'open', '6mlDLORpdK0hUaqy', 'itaque-aduro-ceno', 'https://glittering-mixture.net/', 'https://slimy-sesame.org/', '2025-12-31T13:51:06.221Z', '2025-12-31T00:51:49.797Z', 'Vox crur excepturi cohibeo thymum circumvenio animus careo tredecim laudantium. Tubineus cetera vinco solio territo. Decimus soluta praesentium.', 1, 'https://acidic-earth.org/', 7, 'post', 'audio/opus', 8589754787026657),
  (4, 10, '2025-05-25T18:51:44.639Z', '2025-04-05T06:47:29.061Z', 'Aestivus coniecto aeger cumque correptius vir corrupti. Vesica textor cras deduco clementia. Sufficio solio suscipit amoveo.', 'Delectatio torqueo autem quia super colligo.', 'Traho vomer desipio argentum.', 'publish', 'closed', 'open', '0IQIOWw4AKUwqsQg', 'velum-molestiae-tubineus', 'https://extra-large-ownership.info', 'https://slight-valentine.org', '2025-12-31T10:18:20.210Z', '2025-12-31T07:04:00.459Z', 'Omnis deludo audio animus cunctatio vel cado consuasor vetus cena. Caritas ancilla attollo ciminatio audax. Tego arcus timidus depereo blanditiis.', 1, 'https://front-membership.biz', 10, 'page', 'image/avif', 5679076943480930),
  (5, 7, '2025-02-20T22:00:56.603Z', '2025-04-18T12:38:43.789Z', 'Conicio deprecator valetudo auditor subseco sollers fugit decumbo aspicio. Uberrime varius caput coerceo tollo creptio veritas urbs amoveo corrumpo. Sit vaco reprehenderit depopulo adulatio caelum.', 'Tantum attollo quas sumptus acerbitas crapula amissio supellex.', 'Tumultus talis cuius sponte vulpes quis.', 'publish', 'open', 'open', 'VpVWG9tEwpa2NNVv', 'vilis-saepe-tempore', 'https://charming-nucleotidase.info', 'https://possible-granny.name/', '2025-12-31T17:19:15.160Z', '2025-12-31T19:16:38.202Z', 'Vallum ceno vulariter tergiversatio dolores ulterius. Deludo cum ulterius sponte arbor appello pectus adflicto. Corrigo confido claudeo spiritus vado uberrime talus uxor vobis.', 1, 'https://rusty-breastplate.biz/', 3, 'attachment', 'application/vnd.oasis.opendocument.text', 2980046987191640),
  (6, 4, '2025-07-09T03:49:26.630Z', '2025-03-16T20:21:46.128Z', 'Viridis adsidue crebro repellat allatus. Aperio velociter contigo spes hic volutabrum vorax sub. Curiositas comptus acquiro carbo adamo amicitia bos.', 'Aequitas utpote sordeo eveniet.', 'Decor cinis videlicet deduco.', 'publish', 'closed', 'open', 'WjXdhQWf9qIeBSXd', 'comes-crapula-cedo', 'https://funny-transparency.name/', 'https://orange-bench.biz', '2025-12-31T18:03:01.913Z', '2025-12-31T05:31:11.823Z', 'Atqui copia coepi. Theatrum administratio iusto comparo custodia voveo vel uredo. Eaque terror abduco strenuus stillicidium.', 1, 'https://antique-co-producer.biz', 1, 'post', 'application/vnd.mozilla.xul+xml', 7897652722412107),
  (7, 9, '2025-05-16T00:57:14.696Z', '2025-05-22T04:13:16.308Z', 'Cavus abscido demoror trans. Casso vesco bibo ratione sub iure arcus decimus. Tumultus cicuta delicate cupiditas utor expedita.', 'Versus tergo demulceo certe comes crapula aduro absorbeo cultellus.', 'Una reprehenderit quisquam vestrum.', 'publish', 'open', 'open', 'Gu7TuhG6Jz0HBX3a', 'desino-adeptio-pecus', 'https://guilty-honesty.info', 'https://posh-pendant.biz/', '2025-12-31T10:03:21.661Z', '2025-12-31T23:09:12.165Z', 'Considero clamo thymum thymum vobis delicate. Audax suadeo patior. Solvo absque delego vorax conspergo dolorum curto valens conscendo capillus.', 1, 'https://winged-traffic.org', 3, 'post', 'application/rtf', 5526915362038220),
  (8, 6, '2025-03-29T15:36:50.210Z', '2025-09-22T14:13:53.882Z', 'Aut cursim cui campana est tabesco comprehendo totam. Bibo usus adulatio vicinus vesica ex bellum doloribus. Nostrum verbum amissio non admitto cattus derideo magni calco.', 'Curiositas aduro velut tredecim collum error auctus ultio arbitro.', 'Beatus laboriosam blandior.', 'private', 'open', 'closed', 'JxWjfDhNw9TSF6fT', 'vigilo-curso-cito', 'https://separate-kit.biz', 'https://expensive-other.info/', '2025-12-31T04:08:41.673Z', '2025-12-31T22:10:47.479Z', 'Carus depopulo adeo arceo traho. Triumphus suspendo comburo. Conventus illum suadeo certe.', 1, 'https://writhing-video.com/', 10, 'post', 'video/mpeg', 6192461522639231),
  (9, 6, '2025-07-25T17:12:20.874Z', '2025-06-05T01:34:01.166Z', 'Ubi tertius aperte adsuesco. Tondeo averto infit praesentium curtus cohors iusto toties venia decet. Decens dolores stella triumphus credo voco quidem.', 'Tum ater magni tabella carbo optio.', 'Est molestiae turpis depraedor.', 'publish', 'open', 'open', 'Ngxhs3z663bspjrQ', 'ullam-et-umquam', 'https://negligible-punctuation.name', 'https://first-secrecy.name/', '2025-12-31T08:02:21.773Z', '2025-12-31T12:01:08.020Z', 'Cado occaecati demo coerceo cultellus. Vallum tres animi suggero. Comparo censura sed terreo appositus vulnus.', 1, 'https://lustrous-lashes.biz/', 2, 'post', 'application/x-httpd-php', 7084990211414848),
  (10, 8, '2025-07-13T00:33:23.447Z', '2025-02-27T14:20:16.125Z', 'Socius approbo voco. Volup aveho caries timor cura aspernatur. Amiculum spoliatio surculus conturbo ratione deporto.', 'Pel tibi ratione tollo.', 'Alo adduco depopulo absconditus atrocitas tot vinum magni.', 'publish', 'open', 'open', 'k1zc2de1p9mIR5mV', 'acerbitas-alioqui-accommodo', 'https://well-off-representation.org/', 'https://obedient-widow.biz', '2025-12-31T20:15:58.433Z', '2025-12-31T02:52:23.790Z', 'Curiositas delectus derideo cariosus aspicio cuppedia nulla conicio voluptatibus cupiditate. Ager brevis aegrotatio. Vigilo vicissitudo conicio acquiro decretum vir suscipio.', 1, 'https://potable-meadow.biz', 7, 'post', 'application/octet-stream', 6315442200520302);

-- wp_comments: 10 rows
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES
  (1, 2, 'Lucille Monahan', 'Erick_Kerluke@hotmail.com', 'https://pointless-redesign.biz/', 'bded:efd7:cb7d:d891:fb20:b0ce:4bdb:eaea', '2025-12-13T08:20:24.740Z', '2025-12-06T03:43:47.762Z', 'Ambitus caterva cinis. Atavus compello thymum desolo defero compono. A vir commodi tibi celo.', 4962975939667657, '1', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_15_7) AppleWebKit/592.5.56 (KHTML, like Gecko) Chrome/124.0.9.13 Safari/543.3.3', 'comment', 1, 1),
  (2, 10, 'Dallas Johnson', 'Zachary38@hotmail.com', 'https://marvelous-oil.org/', '133.125.88.97', '2025-05-05T14:43:08.217Z', '2025-12-18T13:38:27.161Z', 'Subvenio civitas blanditiis audeo verecundia denique. Curriculum eligendi defendo uxor pariatur deorsum. Communis somniculosus verto curia ante tunc claro trucido laborum.', 2954602934149935, '1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/543.10.67 (KHTML, like Gecko) Version/16.1 Safari/590.20.58', 'comment', 1, 10),
  (3, 9, 'Samara Orn', 'Van.Legros@yahoo.com', 'https://unripe-nudge.org/', '8.42.59.100', '2025-09-16T20:41:23.012Z', '2025-08-08T23:20:34.448Z', 'Cedo vere conturbo denuncio allatus aveho nemo beatae deprecator celebrer. Modi defetiscor surculus callide tamen clementia modi caput peior. Ante clamo amor cunabula defaeco.', 2771194450511708, '0', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/596.0.35 (KHTML, like Gecko) Version/16.1 Safari/569.48.70', '', 1, 1),
  (4, 6, 'Jamil Jacobs', 'Bria.Morar22@gmail.com', 'https://short-octave.net', '9a01:5b0d:ae98:abf7:2756:ebb0:a3a3:fb9b', '2025-03-10T19:18:09.071Z', '2025-12-13T19:07:16.895Z', 'Verumtamen talis veritas spargo amoveo accusantium. Deinde ait curvo caput. Aedificium basium sustineo sed.', 1227862942860164, '1', 'FakerBot/8.20.18', 'comment', 1, 8),
  (5, 4, 'Josiah Schiller', 'Moshe.Casper@gmail.com', 'https://peppery-plain.org', 'a003:668e:b46a:ce4e:a78a:8dec:fc0b:9b7e', '2025-08-20T14:09:53.690Z', '2025-11-05T13:16:44.629Z', 'Copia auctor thalassinus. Adsum thema vulgo dedecor. Tendo carpo inventore ultio adamo apparatus officiis vetus volup.', 2271021953857282, '1', 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/566.75.45 (KHTML, like Gecko) Version/11_4 Mobile/15E148 Safari/559.61', 'comment', 1, 4),
  (6, 9, 'Peggie Bernier MD', 'Estefania_Morissette46@hotmail.com', 'https://unselfish-longboat.net', '66.180.191.130', '2025-01-16T23:00:35.635Z', '2025-05-04T20:01:07.509Z', 'Appono tibi omnis templum vulgus votum. Tantillus solum causa commemoro verto crinis. Carbo calcar adflicto aureus benigne carus centum varietas crepusculum cometes.', 7996956026011776, '1', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_15_7) AppleWebKit/601.94.44 (KHTML, like Gecko) Chrome/92.4.16.10 Safari/564.1.90', 'comment', 1, 8),
  (7, 4, 'Adrian Bahringer', 'Emely83@yahoo.com', 'https://enraged-ice-cream.org/', '397f:fce6:3ffe:8c89:2c6c:3517:5bf4:5b55', '2025-11-16T10:55:51.786Z', '2025-03-29T02:02:55.802Z', 'Combibo corrupti turpis absconditus. Terror sollicito sonitus socius suffoco vulnero. Vinitor tracto iusto conduco strenuus suadeo.', 8835387404230295, '1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/114.0', 'comment', 1, 10),
  (8, 4, 'Teresa Labadie', 'Jessica_Raynor20@gmail.com', 'https://lost-honesty.biz', 'c9c7:eec3:08dc:756b:cbcf:d0bf:8ce2:c154', '2025-04-27T00:40:58.302Z', '2025-08-22T12:53:56.995Z', 'Conicio consequatur teres cribro accendo abutor suscipit demonstro sopor spargo. Earum sonitus eum constans. Excepturi uxor ventus saepe accusamus cariosus terreo vitiosus tondeo.', 8813488345821386, '1', 'Googlebot/2.1 (+http://www.google.com/bot.html)', 'comment', 1, 2),
  (9, 3, 'Larry Muller', 'Silvia.Okuneva@gmail.com', 'https://warped-inspection.com', 'd766:c4fc:57d5:cbd8:e586:a868:2ba2:f587', '2025-02-20T14:03:17.868Z', '2025-01-31T21:51:19.236Z', 'Odio cotidie tollo amaritudo voco in strues vester calamitas nesciunt. Stips uxor correptius dolores vado ex. Victus amissio titulus curia thorax adficio vilicus corporis tepesco cognatus.', 4774858760434900, '0', 'FakerBot/2.19.17', '', 1, 6),
  (10, 9, 'Allison Hills', 'Rosa49@hotmail.com', 'https://repentant-dream.info/', '37.254.170.119', '2025-01-28T23:37:02.164Z', '2025-06-11T12:48:58.441Z', 'Vindico accedo terreo. Verbum apostolus corrigo depopulo tertius angustus. Vulticulus conitor audax antiquus vos.', 2224460960334747, '1', 'Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/113.0', 'comment', 1, 10);

-- wp_commentmeta: 10 rows
INSERT INTO `wp_commentmeta` (`meta_id`, `comment_id`, `meta_key`, `meta_value`) VALUES
  (1, 8, 'vere', NULL),
  (2, 5, 'voluptatibus', 'Voluptate tripudio maiores traho.'),
  (3, 9, 'clam', 'Clam ademptio paulatim viscus.'),
  (4, 4, 'vesco', NULL),
  (5, 10, 'apud', 'Ago aufero apparatus tonsor careo subvenio peccatus.'),
  (6, 7, 'explicabo', 'Absorbeo reprehenderit deduco.'),
  (7, 8, 'minus', 'Capto volo defetiscor totam aequus comedo harum aegrus voluptatibus delinquo.'),
  (8, 4, 'ut', 'Ante calcar cursus denuncio dens spoliatio deduco vomito subseco vilitas.'),
  (9, 8, 'appositus', 'Libero dicta textor centum comes admitto carmen viriliter vigilo explicabo.'),
  (10, 5, 'volutabrum', NULL);

-- wp_postmeta: 10 rows
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
  (1, 1, 'vesco', NULL),
  (2, 6, 'defungo', NULL),
  (3, 10, 'calcar', 'Tunc administratio arguo annus amo vomer coniuratio ascit vigor.'),
  (4, 8, 'defaeco', NULL),
  (5, 10, 'utrum', 'Spero dolor repellendus asper auctus.'),
  (6, 7, 'sollicito', 'Verbera aggero vos non victoria.'),
  (7, 2, 'confero', NULL),
  (8, 10, 'xiphias', NULL),
  (9, 5, 'utpote', 'Nam adicio spes tot vereor articulus cito totam aetas.'),
  (10, 1, 'arbor', NULL);

-- wp_usermeta: 10 rows
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
  (1, 4, 'ullus', 'Amet arca denique vulgaris nam utrum voluptatibus ciminatio nam.'),
  (2, 10, 'vinum', 'Via distinctio calculus.'),
  (3, 2, 'volo', 'Suus accedo vesco toties avarus deprecator stabilis dolor benevolentia vacuus.'),
  (4, 3, 'thalassinus', 'Urbanus accedo corpus vomica amicitia est alioqui auditor aer decerno.'),
  (5, 10, 'adhuc', NULL),
  (6, 10, 'fuga', 'Ante tui aegrotatio pariatur.'),
  (7, 3, 'cauda', 'Aegre aetas eligendi demulceo minus.'),
  (8, 1, 'terror', 'Denuncio sunt patior tumultus quam viscus civis autus angelus.'),
  (9, 1, 'depulso', 'Mollitia similique tonsor.'),
  (10, 9, 'accusantium', 'Aureus torrens inflammatio crustulum viriliter cubo tumultus cognomen sed aeternus.');

COMMIT;
