-- Generated by auto-seed
-- tool: auto-seed
-- model: openai/gpt-4o-mini
-- seed: 1939961296
-- rows: 120
-- tables: 12

-- Optional reset (uncomment if you want a clean slate before seeding):
-- DELETE FROM `wp_usermeta`;
-- DELETE FROM `wp_postmeta`;
-- DELETE FROM `wp_commentmeta`;
-- DELETE FROM `wp_comments`;
-- DELETE FROM `wp_posts`;
-- DELETE FROM `wp_users`;
-- DELETE FROM `wp_termmeta`;
-- DELETE FROM `wp_term_relationships`;
-- DELETE FROM `wp_term_taxonomy`;
-- DELETE FROM `wp_terms`;
-- DELETE FROM `wp_options`;
-- DELETE FROM `wp_links`;

BEGIN;

-- wp_links: 10 rows
INSERT INTO `wp_links` (`link_id`, `link_url`, `link_name`, `link_image`, `link_target`, `link_description`, `link_visible`, `link_owner`, `link_rating`, `link_updated`, `link_rel`, `link_notes`, `link_rss`) VALUES
  (1, 'https://alert-thorn.biz/', 'aureus', 'https://picsum.photos/seed/zn4xB/3468/1813', 'architecto', 'Vicissitudo vix decor dedico suffragium tamisium defleo ait.', 'yes', 1, 0, '2025-07-13T14:49:29.764Z', 'viduo', 'Paulatim benigne vulgivagus corpus coerceo cibo cura.', 'https://artistic-horde.com'),
  (2, 'https://mealy-venom.org/', 'sunt', 'https://picsum.photos/seed/pnQ6voIs/338/3115', 'turbo', 'Caveo nulla curiositas.', 'yes', 1, 1, '2025-12-04T11:18:03.124Z', 'suspendo', 'Vereor admoveo temporibus cernuus adimpleo valeo.', 'https://spirited-heartache.biz/'),
  (3, 'https://flawless-ocelot.com/', 'surculus', 'https://picsum.photos/seed/nwkYNFWNKF/2405/1829', 'pecto', 'Surculus vilitas vero magnam terebro.', 'yes', 1, 0, '2025-09-26T14:41:51.591Z', 'xiphias', 'Votum corrumpo recusandae sponte aptus venia tremo aeneus.', 'https://far-off-adrenalin.net/'),
  (4, 'https://dense-slipper.biz', 'harum', 'https://picsum.photos/seed/xBuJHIJ/2128/2204', 'cohibeo', 'Conqueror depopulo carus astrum timidus.', 'yes', 1, 0, '2025-12-28T07:17:22.042Z', 'caecus', 'Calco usque arca earum aveho argentum.', 'https://unimportant-jacket.biz/'),
  (5, 'https://talkative-lay.org', 'eligendi', 'https://picsum.photos/seed/xuTHFgBI/3345/1712', 'delibero', 'Optio verto aggero soleo vorax sumptus.', 'yes', 1, 0, '2025-03-27T14:35:28.552Z', 'unus', 'Pauper uxor virtus amaritudo ad abbas.', 'https://lucky-address.name'),
  (6, 'https://appropriate-bowling.com/', 'textor', 'https://picsum.photos/seed/6CIsb8Pi/1017/3769', 'arguo', 'Aliquam corroboro ubi totam neque adsuesco.', 'yes', 0, 1, '2025-04-30T14:02:31.024Z', 'aegrotatio', 'Amita blanditiis sumo ascit possimus villa vilis vergo accusamus.', 'https://glossy-knight.com'),
  (7, 'https://creamy-climb.net', 'voluptate', 'https://picsum.photos/seed/Md6ia6G/2218/2583', 'delectatio', 'Excepturi callide consequuntur sunt alias terra tristis eveniet solum curvo.', 'yes', 1, 0, '2025-12-26T04:19:06.609Z', 'comptus', 'Denuncio depereo terror eos tenax capitulus tener.', 'https://familiar-injunction.name'),
  (8, 'https://accurate-disadvantage.info/', 'clibanus', 'https://picsum.photos/seed/63lhSkv2c/3635/2050', 'alii', 'Delibero unus est ventosus textus commodi quia.', 'no', 1, 1, '2025-03-12T03:20:08.008Z', 'cito', 'Texo aegrotatio colligo alias eveniet.', 'https://firm-vibration.info/'),
  (9, 'https://secret-injunction.org', 'dedecor', 'https://picsum.photos/seed/WhOLZxmD/1474/1412', 'depopulo', 'Corporis quam amoveo ars adeptio vulgus ea crepusculum sodalitas coaegresco.', 'yes', 1, 1, '2025-05-06T07:35:59.589Z', 'vesco', 'Apto corporis virgo solium caute confero dicta valens.', 'https://huge-litter.net/'),
  (10, 'https://damaged-issue.org/', 'iste', 'https://picsum.photos/seed/f4Ra2FMns0/91/1094', 'suus', 'Demergo accusamus despecto venia tum.', 'yes', 0, 0, '2025-02-21T10:09:19.077Z', 'xiphias', 'Tersus clementia crinis coniecto aequitas demonstro velum ars surculus.', 'https://radiant-climb.info/');

-- wp_options: 10 rows
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
  (1, 'autem', 'Tonsor depono tergeo substantia excepturi clam complectus capto.', 'yes'),
  (2, 'creator', 'Adstringo coerceo denuo depopulo pectus crapula stillicidium testimonium.', 'yes'),
  (3, 'valeo', 'Cumque appositus sponte arbitro deleniti voluntarius balbus uter.', 'yes'),
  (4, 'vulnero', 'Fugiat avarus utrum substantia attero minus.', 'yes'),
  (5, 'ullam', 'Comparo quasi utrimque.', 'yes'),
  (6, 'callide', 'Verecundia vix tenuis non solum.', 'yes'),
  (7, 'vesica', 'Denuncio conor deprimo debitis cornu tempore magni animus vestigium.', 'yes'),
  (8, 'cometes', 'Tum caelestis uxor.', 'yes'),
  (9, 'vox', 'Harum taceo spargo.', 'yes'),
  (10, 'decretum', 'Ea trado benevolentia.', 'yes');

-- wp_terms: 10 rows
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
  (1, 'cauda', 'caute-armarium-astrum', 0),
  (2, 'mollitia', 'tantillus-conor-vomito', 0),
  (3, 'auxilium', 'viduo-varietas-audio', 0),
  (4, 'allatus', 'usque-cribro-amitto', 0),
  (5, 'virgo', 'caecus-cibo-quo', 0),
  (6, 'angelus', 'apud-creo-patruus', 0),
  (7, 'concedo', 'cupio-sonitus-callide', 0),
  (8, 'defleo', 'sequi-temperantia-utilis', 0),
  (9, 'denuo', 'voveo-basium-terebro', 0),
  (10, 'pecus', 'cernuus-accedo-stultus', 0);

-- wp_term_taxonomy: 10 rows
INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
  (1, 6, 'ratione', 'Sophismata aut summisse inflammatio subnecto ultra. Altus nemo illo volo suggero. Tametsi tergeo est comitatus caterva tunc.', 0, 0),
  (2, 3, 'tactus', 'Constans arma bellum votum considero. Somnus caelum solitudo contabesco culpa tego modi curriculum. Tabernus collum necessitatibus deprecator cur aperio alioqui suspendo quas.', 0, 0),
  (3, 3, 'eligendi', 'Angelus sponte totidem corporis damnatio possimus. Subiungo cognomen decimus sui amicitia thesaurus solum. Depopulo demitto tergiversatio curo deserunt.', 0, 0),
  (4, 1, 'verecundia', 'Vociferor tero denique basium cras demum defluo. Carmen ceno turbo certe sui veritas. Maiores adfectus arca blanditiis creator coruscus cohors.', 1, 0),
  (5, 10, 'causa', 'Verus abutor campana thesis adipiscor. Clementia defendo ustilo vereor optio. Sum articulus truculenter cibus advoco.', 0, 0),
  (6, 2, 'excepturi', 'Colligo surculus caelum adiuvo. Tardus tabgo brevis vesper appello crux vespillo vester. Valetudo vir copiose cernuus viscus.', 1, 0),
  (7, 7, 'reiciendis', 'Pax sodalitas solium. Nihil curo ciminatio cognatus supplanto torqueo capio commemoro. Vesica copia vilis atrocitas sol et.', 0, 0),
  (8, 9, 'summopere', 'Toties circumvenio combibo acquiro debitis aegre creber ab. Cado taedium verbera amicitia neque ciminatio urbs solio tabgo. Turba peior crustulum cariosus.', 1, 0),
  (9, 10, 'velum', 'Adficio ago casus teres appono tristis. Defessus aedificium laudantium talus. Minus admiratio vir alioqui cognatus vigilo circumvenio adfero eveniet.', 1, 0),
  (10, 6, 'velut', 'Admitto temeritas adeptio bene amet varius contego vociferor. Subnecto curia absque campana inventore admitto beatae dicta minus. Balbus cuius tersus.', 0, 0);

-- wp_term_relationships: 10 rows
INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
  (1, 3, 0),
  (2, 2, 0),
  (3, 8, 0),
  (4, 4, 0),
  (5, 6, 0),
  (6, 6, 0),
  (7, 8, 0),
  (8, 1, 0),
  (9, 3, 0),
  (10, 6, 0);

-- wp_termmeta: 10 rows
INSERT INTO `wp_termmeta` (`meta_id`, `term_id`, `meta_key`, `meta_value`) VALUES
  (1, 10, 'solitudo', NULL),
  (2, 9, 'aptus', 'Vaco campana arma usitas thesis.'),
  (3, 4, 'defungo', 'Terga caries vestrum crastinus facere attero bos carpo.'),
  (4, 8, 'pax', 'Vereor undique pel depraedor adsum.'),
  (5, 10, 'barba', 'Delego iure agnitio sapiente combibo somnus conscendo vitiosus terga caelestis.'),
  (6, 4, 'verumtamen', NULL),
  (7, 9, 'bellum', NULL),
  (8, 9, 'super', 'Tripudio similique calculus tenuis.'),
  (9, 2, 'temperantia', NULL),
  (10, 2, 'commodi', 'Basium tener subiungo teres una tutamen acervus avaritia.');

-- wp_users: 10 rows
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
  (1, 'Paul_Rice39', '2HGUBmhYbElc_Bm', 'Tanya_Maggio42', 'Sean.Frami@gmail.com', 'https://violent-publication.com', '2025-10-06T00:18:25.818Z', 'IwUBlobIv4Jr8x4', 0, 'Luther Stracke'),
  (2, 'Wm44', 'YfgDgHsUlOqylmy', 'Lisa.Muller', 'Bridget_Oberbrunner@yahoo.com', 'https://nimble-cutlet.net', '2025-10-24T00:42:34.175Z', 'MTlKPCIAK3jJhcC', 0, 'Kevin Marks'),
  (3, 'Mathilde.Jaskolski', 'h5zKTK57PY_Wcmr', 'Eryn.Schneider', 'Sonny.Keebler@hotmail.com', 'https://sociable-gazebo.net', '2025-02-13T12:59:54.670Z', 'pecgIynbG34UMfV', 0, 'Deontae Bernier'),
  (4, 'Leland_Donnelly58', 'tzpZuqp4Bnhe9y6', 'Frankie76', 'Dale.Schamberger53@hotmail.com', 'https://basic-complication.info', '2025-02-08T12:00:43.868Z', 'aLUrQ4nPSvOE9OU', 0, 'Imogene Hammes PhD'),
  (5, 'Derick42', '_cdwxLm4qvpgwC1', 'Viola.Thompson99', 'Vera.Reichel@yahoo.com', 'https://ill-fated-flame.info', '2025-07-07T16:41:36.483Z', 'hNdGFMIGPToIbbq', 0, 'Marlon Wyman'),
  (6, 'Jana.Pfeffer67', 'Qlk2rrneFqv9zun', 'Logan72', 'Demarco_Kulas@hotmail.com', 'https://thorny-exhaust.net/', '2025-10-03T13:29:03.723Z', 'kqe3rUusvSe7CzS', 0, 'Oma Johnson I'),
  (7, 'Heather.Johns89', 'rXCUXrhHihO4EX9', 'Chester.Schamberger84', 'Virginia66@yahoo.com', 'https://international-cope.com/', '2025-11-07T15:32:11.066Z', 'n55MmSB3LWHWbsj', 0, 'Frederic Jakubowski'),
  (8, 'Gerard_Pollich', 'chVOteULBgDzWBP', 'Lempi_Johnston', 'Alyssa_Padberg@hotmail.com', 'https://shimmering-adult.com', '2025-02-05T17:37:21.270Z', 'LByqCaTQj4B6t4P', 0, 'Eileen Volkman'),
  (9, 'Godfrey_Yost77', 'gmBbI05Mg_DNovv', 'Antonietta80', 'Chelsea_Wiegand11@yahoo.com', 'https://primary-switchboard.name/', '2025-12-25T06:26:32.348Z', 'H13nkgVPBcF1gEJ', 0, 'Zoie Feil-Anderson'),
  (10, 'Morton86', 'Fp2sYAIBcNbxfVp', 'Dexter56', 'Domingo77@yahoo.com', 'https://fragrant-flight.biz', '2025-08-26T11:35:31.821Z', '0zjzG8cZ6gkDjcN', 0, 'Dorian Glover');

-- wp_posts: 10 rows
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
  (1, 4, '2025-12-16T13:43:32.614Z', '2025-04-03T06:10:04.185Z', 'Crebro cognomen sortitus. Debeo barba illum. Velit corrupti vigilo summopere sum stella sit tonsor.', 'Aequus torrens xiphias aut vix.', 'Verto avaritia ipsa vilitas animadverto commodo magnam adnuo officiis.', 'publish', 'open', 'closed', 'GzTisPZoEjgNPoX', 'fugit-tribuo-adulatio', 'Tabgo tenax explicabo voro ver tristis sed.', 'Sufficio traho vergo bibo thymbra facere taceo argumentum.', '2025-03-11T15:23:25.319Z', '2025-11-22T18:36:08.681Z', 'Apparatus ustilo vespillo abutor suppono numquam. Amaritudo acer accedo pecco ciminatio calamitas ut strues. Tunc xiphias abundans decimus totam absens quibusdam adamo.', 0, 'https://proper-longboat.org/', 0, 'accendo', 'ager', 0),
  (2, 10, '2025-11-04T13:20:28.332Z', '2025-09-26T10:16:31.614Z', 'Aureus aut demens cornu vinco sunt. Audentia cubicularis voluptatem tenus tubineus repellat venia theca vado. Cunabula basium cuius ex comparo contigo tristis.', 'Porro ambulo complectus.', 'Benevolentia quae caput chirographum cibus vomito verus argentum.', 'draft', 'open', 'open', 'Ql9rJLyQ7zqmNQ3', 'allatus-bestia-vis', 'Artificiose quas consectetur concido tui circumvenio.', 'Minima angustus deludo bos abutor.', '2025-12-24T16:45:48.834Z', '2025-10-28T16:11:52.067Z', 'Crapula terminatio accusamus tepesco. In uter sequi. Cui brevis spes sunt venio demulceo tandem eligendi.', 1, 'https://authorized-negotiation.com/', 0, 'conduco', 'vulgus', 0),
  (3, 5, '2025-04-12T20:56:57.554Z', '2025-07-16T07:44:33.442Z', 'Solum demo certe confugo sequi tolero adicio vesco. Voluptatibus demo testimonium dolores doloremque addo vilicus tantum thorax deripio. Consectetur tremo quam cedo turba vehemens calculus.', 'Victoria amitto demergo cultura.', 'Comprehendo patruus vero ut umbra abeo.', 'publish', 'closed', 'open', 'kwzVX8L4KFiEQQ3', 'voveo-dolorum-tersus', 'Amoveo cernuus testimonium occaecati.', 'Ait et conduco cohaero solitudo aeger conscendo.', '2025-07-17T11:49:20.025Z', '2025-08-14T19:20:15.345Z', 'Deprecator vero doloremque beatae vergo spes. Sonitus tenetur voro paulatim. Cenaculum acquiro pecto crudelis.', 1, 'https://left-chasuble.org', 0, 'super', 'ascisco', 0),
  (4, 3, '2025-05-05T16:48:41.418Z', '2025-10-30T21:11:14.158Z', 'Barba studio vapulus tutis exercitationem laudantium demergo vulgaris ait territo. Talus angulus clamo somniculosus sollicito voluptas tam soleo. Officiis admoveo amplus carbo volup attero similique cibus unde.', 'Collum ullus tandem tabesco creber.', 'Sodalitas demo autem conscendo aut dolorem aut vociferor denuo aequitas.', 'publish', 'open', 'open', 'EkyZ9VQrwXaeITC', 'voluptatibus-derideo-adicio', 'Alveus iusto cerno solutio vomica trado cribro earum acsi aequus.', 'Denique adopto ut cotidie.', '2025-06-21T03:47:25.910Z', '2025-11-10T18:02:39.214Z', 'Sol bellicus aperte ventosus quisquam contabesco velociter claudeo. Vobis termes acsi aiunt sollers cauda degusto campana quisquam teneo. Urbanus totam collum.', 1, 'https://likable-compromise.name', 0, 'strenuus', 'crepusculum', 0),
  (5, 2, '2025-04-10T08:16:05.560Z', '2025-02-10T20:31:17.164Z', 'Qui adficio antiquus. Somnus compello tot quidem dolorem clamo textus nesciunt. Vapulus maxime solium.', 'Error arx articulus desparatus catena.', 'Commemoro degero dedecor trans ascit quod.', 'publish', 'open', 'open', 'lAaDnNyBpanfGIj', 'vergo-coruscus-subiungo', 'Tactus auctor sperno creber avarus.', 'Studio stillicidium conventus delectatio denique crustulum bene alveus.', '2025-09-09T09:56:46.612Z', '2025-03-26T05:56:10.684Z', 'Demum accusator defero adficio ver distinctio ait victoria coniuratio quis. Blanditiis alius candidus accusator adaugeo cornu timor depopulo sollers. Omnis tamisium solium adicio coniuratio arbustum subvenio appono aegrotatio.', 0, 'https://silver-cope.net', 0, 'qui', 'tripudio', 0),
  (6, 8, '2025-06-29T13:34:43.333Z', '2025-10-14T20:59:14.053Z', 'Conscendo abstergo conforto ara. Curatio vigor umquam deinde blandior viduo. Varius sequi angelus quas impedit.', 'Neque verbera confido curto tenetur.', 'Ter cibo virga ancilla comptus consequuntur.', 'publish', 'closed', 'open', 'FolQsfS_LvvcQAw', 'adsuesco-adulescens-amet', 'Rerum calcar tergo rerum.', 'Comburo sunt deficio.', '2025-02-21T16:36:07.494Z', '2025-04-21T23:36:57.952Z', 'Aro temeritas calamitas arca attonbitus solio sono decet vado. Aeternus crastinus verbera defluo consequuntur virga. Tredecim suffoco cum sunt spectaculum terra pauci.', 1, 'https://remarkable-corral.org', 0, 'valens', 'sonitus', 0),
  (7, 4, '2025-09-28T01:45:09.929Z', '2025-08-12T22:59:29.278Z', 'Conforto terminatio tyrannus. Virtus commodi callide artificiose tibi officiis tenax dolores video. Patria curtus vix tabella voluptatem nisi asper ex attero suasoria.', 'Adhuc texo cauda delectatio baiulus voveo vilitas deputo officia pecus.', 'Deleniti pecus solus in atrocitas damno ager amoveo compono.', 'publish', 'closed', 'open', 'WjYvyR5OgJRGvXi', 'teneo-laborum-adinventitias', 'Vobis nesciunt aqua veritatis.', 'Rem ciminatio mollitia ducimus arcus ulterius pel auditor debitis circumvenio.', '2025-11-01T03:24:55.077Z', '2025-01-30T17:39:16.480Z', 'Curo tendo dolores. Tergo deludo decipio contabesco quis tepesco. Combibo consuasor dedecor bis tum corrupti succedo.', 0, 'https://optimal-vision.com', 0, 'crudelis', 'verbera', 0),
  (8, 8, '2025-05-26T11:55:51.362Z', '2025-12-04T16:04:17.974Z', 'Alioqui cumque cognatus vereor abduco casus saepe baiulus collum. Temporibus reprehenderit earum verus adstringo victus curia impedit solitudo aro. Cupiditas sol coniuratio ventus speciosus ventosus cursus spiculum corrigo decumbo.', 'Et defendo odio clibanus.', 'Vorax concido careo teneo sponte volo suscipit vestigium laudantium.', 'publish', 'closed', 'closed', 'yoL7YN2NaSIP5zO', 'video-adhaero-usque', 'Vestrum volva solutio aeger suppono.', 'Voluntarius calculus attero debitis vivo arbitro caelum expedita nulla carpo.', '2025-05-17T22:15:38.375Z', '2025-03-02T23:09:54.037Z', 'Vinum alias turbo sophismata amplitudo vilicus peccatus. Vilis sursum possimus sapiente demitto sunt itaque tero spectaculum inventore. Cena defungo itaque socius.', 1, 'https://descriptive-digestive.com', 0, 'corpus', 'consuasor', 0),
  (9, 10, '2025-07-29T02:02:31.335Z', '2025-11-16T19:15:03.667Z', 'Constans tactus infit velut combibo. Sub alii vestrum tergum tolero tristis. Voco sub carcer necessitatibus atrocitas video clamo molestias spero demergo.', 'Asper sto curo.', 'Eius videlicet necessitatibus.', 'publish', 'open', 'open', 'sv2WOKPpQ_PqrlI', 'ut-deputo-stillicidium', 'Aiunt somniculosus supra custodia defungo.', 'Ustulo constans tertius temeritas suadeo.', '2025-11-27T00:00:45.613Z', '2025-07-10T00:28:24.778Z', 'Arcesso adaugeo vorago adipisci statim eaque approbo vespillo. Trado aptus tardus comminor. Caelestis suppellex bis aliquid.', 0, 'https://witty-perfection.org/', 0, 'delibero', 'colo', 0),
  (10, 8, '2025-11-23T04:59:23.259Z', '2025-08-15T15:18:20.687Z', 'Vomica apparatus caterva conculco totus. Bibo utor alii adipiscor tenuis. Atqui aegrotatio hic capillus.', 'Eum tepidus summa numquam admoneo.', 'Ustilo veritatis varius thymbra amo subseco asperiores.', 'publish', 'closed', 'open', 'rknM7y7c6xPK_fd', 'desolo-valens-canis', 'Pauci theatrum asporto.', 'Certus veritatis censura copiose.', '2025-01-28T08:07:41.426Z', '2025-05-01T07:38:48.016Z', 'Impedit coerceo uredo arto uredo adficio arca. Surgo ara color appono dens verbera degusto callide. Labore deleo comitatus adduco testimonium officiis admiratio confido uredo voluptate.', 1, 'https://qualified-newsstand.info', 0, 'virtus', 'bellicus', 0);

-- wp_comments: 10 rows
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES
  (1, 7, 'Efren West', 'Sherri.Schoen@gmail.com', 'https://gorgeous-going.com/', '71.108.228.7', '2025-03-13T08:08:00.729Z', '2025-10-06T03:15:01.923Z', 'Debeo teres defleo occaecati bardus audax somnus. Aeneus desparatus solutio temptatio. Carmen suppono velociter cilicium est utilis.', 0, 'no', 'timidus', 'benigne', 0, 8),
  (2, 1, 'Taylor Kreiger', 'Unique.Rodriguez61@hotmail.com', 'https://neighboring-footrest.biz', '113.168.228.46', '2025-08-16T04:10:47.994Z', '2025-02-10T14:24:42.873Z', 'Aliqua repellat bellum consequatur strenuus error conscendo voluptates. Alienus canonicus contabesco cohibeo alioqui canonicus. Confugo ambulo ver ago saepe peior.', 0, 'yes', 'appositus', 'carmen', 0, 10),
  (3, 4, 'Isaac Prosacco', 'Rachael.Emard@hotmail.com', 'https://well-documented-instruction.net', 'd7ea:f0d3:f1ef:c3cb:184d:ee3d:8efb:dbf1', '2025-06-28T18:05:47.576Z', '2025-12-30T04:56:52.461Z', 'Utrimque excepturi odio tabula vulticulus. Quisquam valens tondeo adulescens. Dignissimos tabernus ambitus cuius dolores stipes curvo adinventitias.', 0, 'no', 'abscido', 'deorsum', 0, 2),
  (4, 10, 'Orlando Jaskolski', 'Ada_Volkman@hotmail.com', 'https://filthy-transparency.org/', '207.128.52.182', '2025-01-18T10:37:13.717Z', '2025-09-10T19:58:09.930Z', 'Corona cattus amissio deripio alienus velum. Acidus aestivus audacia. Ea decumbo ulciscor sortitus decet.', 0, 'yes', 'optio', 'supra', 0, 4),
  (5, 10, 'Durward Monahan', 'Kelli_Schmeler@yahoo.com', 'https://bony-shark.net/', 'af7b:2fd6:d83c:ddd4:936f:0dc8:db8a:174f', '2025-10-28T06:30:06.731Z', '2025-03-02T20:28:55.814Z', 'Venia caritas deficio avarus vacuus decerno. Thalassinus vorax textor crastinus voluptas vulnus bibo commodo. Veritatis audentia vir tyrannus bene voluptate aro at ipsa volaticus.', 0, 'yes', 'creber', 'accusantium', 0, 1),
  (6, 5, 'Carmella Friesen I', 'Ernesto_Yundt@gmail.com', 'https://lazy-devastation.biz/', '6c07:f237:afda:ef49:bace:9123:fc8a:4aae', '2025-09-23T02:43:04.721Z', '2025-05-27T19:12:02.640Z', 'In vis debeo cupressus. Rerum autus depono certus cetera perspiciatis utrimque. Delinquo tabgo viscus accusamus sulum spiritus cognomen.', 0, 'no', 'ante', 'adversus', 0, 10),
  (7, 5, 'Harriet Johns', 'Kylee_Reinger@yahoo.com', 'https://dependable-wallaby.com', '114.15.20.176', '2025-09-30T12:38:09.786Z', '2025-11-29T08:31:49.034Z', 'Statim pauper supra cunae amissio. Crebro cogo officia ceno angustus apud cuius ullus cubo voco. Nisi adsum qui.', 0, 'pending', 'delinquo', 'unus', 0, 4),
  (8, 1, 'Taya Satterfield', 'Wilfred_Funk@yahoo.com', 'https://fortunate-warming.name/', 'f6e8:abf1:c8df:e167:5cb3:19ca:23b6:ccc7', '2025-04-15T02:50:41.145Z', '2025-07-29T07:50:25.386Z', 'Cresco adipisci demergo vobis cresco usus vulgus. Usitas vulariter depulso textus coniuratio deserunt autus amplexus vulpes benigne. Adduco molestiae adsum.', 0, 'yes', 'necessitatibus', 'consequuntur', 0, 2),
  (9, 1, 'Juwan Konopelski', 'Stella.Terry6@yahoo.com', 'https://husky-plastic.biz', '3264:a31f:dc70:2d9d:c7ea:831f:aace:e4a7', '2025-05-08T17:26:43.189Z', '2025-06-04T22:37:54.629Z', 'Ulciscor vigilo socius. Acsi tamisium recusandae rem tamdiu. Vapulus subseco vesica.', 0, 'no', 'odio', 'undique', 0, 7),
  (10, 8, 'Sammy Reinger', 'Melinda78@gmail.com', 'https://impure-schedule.info', '7e0c:adfa:2a16:89df:a3c7:27ec:d35e:3bb4', '2025-09-05T09:11:57.765Z', '2025-01-24T11:01:56.501Z', 'Adfectus tero cunae velociter undique trucido coadunatio aperte neque denego. Corrupti modi beatus tutamen cunctatio accedo ex tersus. Spiritus itaque conventus quas arcesso.', 0, 'yes', 'caritas', 'exercitationem', 0, 5);

-- wp_commentmeta: 10 rows
INSERT INTO `wp_commentmeta` (`meta_id`, `comment_id`, `meta_key`, `meta_value`) VALUES
  (1, 4, 'appello', 'Speculum totidem catena pel utrum beatae averto iste coniecto.'),
  (2, 9, 'coaegresco', 'Viridis caveo conicio appono id chirographum coma sollicito reiciendis incidunt.'),
  (3, 1, 'pariatur', 'Depopulo tabula tam suppellex libero tibi aspicio.'),
  (4, 10, 'cupiditate', 'Una cunae defleo cilicium votum vinculum cupio.'),
  (5, 8, 'cubo', NULL),
  (6, 5, 'conspergo', 'Crepusculum pariatur cogito avaritia cicuta quo.'),
  (7, 4, 'altus', 'Cogo basium voluptas iste esse aqua uxor illum.'),
  (8, 8, 'vito', NULL),
  (9, 9, 'pariatur', NULL),
  (10, 4, 'cavus', NULL);

-- wp_postmeta: 10 rows
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
  (1, 5, 'deinde', 'Vivo vere molestias ustulo consequuntur uter.'),
  (2, 5, 'civitas', NULL),
  (3, 6, 'error', 'Concedo veritatis ex ullam argumentum studio tonsor.'),
  (4, 9, 'baiulus', 'Ad annus surgo sponte vere venio.'),
  (5, 5, 'carpo', 'Terror socius textilis bos omnis coaegresco.'),
  (6, 10, 'quam', 'Aestas correptius pauper succedo vociferor tremo.'),
  (7, 2, 'ager', 'Saepe astrum demergo cattus.'),
  (8, 3, 'ventus', 'Reprehenderit vix vere cunabula considero peior tracto.'),
  (9, 10, 'ancilla', 'Canonicus tertius tener tendo tam ara quae solitudo.'),
  (10, 7, 'tersus', 'Damnatio cogo adulescens.');

-- wp_usermeta: 10 rows
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
  (1, 8, 'deprimo', NULL),
  (2, 4, 'iusto', NULL),
  (3, 7, 'campana', 'Attonbitus similique comedo.'),
  (4, 3, 'substantia', NULL),
  (5, 2, 'subvenio', 'Rerum vita creo antiquus valetudo dignissimos.'),
  (6, 8, 'ater', NULL),
  (7, 2, 'ante', NULL),
  (8, 9, 'depulso', 'Coepi claro super vergo solium voluptas decumbo architecto acceptus libero.'),
  (9, 9, 'conqueror', NULL),
  (10, 9, 'circumvenio', 'Coadunatio antiquus tamquam adhaero argumentum triduana excepturi usus iure tempora.');

COMMIT;
