-- Generated by auto-seed
-- tool: auto-seed
-- model: openai/gpt-4o-mini
-- seed: 1377843614
-- rows: 120
-- tables: 12

-- Optional reset (uncomment if you want a clean slate before seeding):
-- DELETE FROM `wp_usermeta`;
-- DELETE FROM `wp_postmeta`;
-- DELETE FROM `wp_commentmeta`;
-- DELETE FROM `wp_comments`;
-- DELETE FROM `wp_posts`;
-- DELETE FROM `wp_users`;
-- DELETE FROM `wp_termmeta`;
-- DELETE FROM `wp_term_relationships`;
-- DELETE FROM `wp_term_taxonomy`;
-- DELETE FROM `wp_terms`;
-- DELETE FROM `wp_options`;
-- DELETE FROM `wp_links`;

BEGIN;

-- wp_links: 10 rows
INSERT INTO `wp_links` (`link_id`, `link_url`, `link_name`, `link_image`, `link_target`, `link_description`, `link_visible`, `link_owner`, `link_rating`, `link_updated`, `link_rel`, `link_notes`, `link_rss`) VALUES
  (1, 'https://athletic-duffel.info/', 'denego', 'tersus thorax articulus', '_blank', 'Sordeo aliqua caelum tempus adficio textilis.', 'N', 1, 1, '2025-12-31T21:27:28.856Z', 'altus', 'Amissio surculus comminor curriculum.', 'https://elegant-pecan.net/'),
  (2, 'https://silent-coliseum.info', 'terreo', 'suscipit cogo cresco', '_self', 'Damnatio comprehendo adfectus virgo officiis cotidie cras taceo conicio.', 'Y', 2, 2, '2025-12-31T10:34:33.663Z', 'tracto', 'Abstergo aptus ab.', 'https://crooked-haircut.name/'),
  (3, 'https://able-punctuation.biz/', 'tabernus', 'laudantium vobis in', '_blank', 'Perferendis creber tersus.', 'Y', 3, 3, '2025-12-31T05:55:18.181Z', 'desino', 'Conitor amo vulariter corona comis depereo aliquam summa.', 'https://tedious-account.info'),
  (4, 'https://pleasant-doubter.name/', 'absorbeo', 'substantia nisi tabernus', '_blank', 'Tardus eligendi stillicidium theca delinquo aetas tempus casus deficio.', 'Y', 4, 4, '2025-12-31T15:25:41.017Z', 'barba', 'Benigne at valens ager collum adfero sum.', 'https://married-plain.biz'),
  (5, 'https://similar-armchair.org', 'audax', 'porro delectus attero', '_self', 'Expedita vado nihil stabilis cogo.', 'Y', 5, 5, '2025-12-31T00:30:43.741Z', 'defendo', 'Uxor odio demonstro annus tamisium totidem compono.', 'https://unsightly-scarification.net/'),
  (6, 'https://suburban-piglet.name', 'vix', 'tener adsum nostrum', '_self', 'Tolero crustulum decor sono arto clamo vaco fugit depereo.', 'Y', 6, 6, '2025-12-31T05:59:01.747Z', 'comedo', 'Suppellex administratio adopto.', 'https://legal-cook.biz/'),
  (7, 'https://busy-tentacle.com', 'aspicio', 'asperiores vero explicabo', '_self', 'Ancilla corpus molestias alius suscipit addo celebrer canis.', 'Y', 7, 7, '2025-12-31T15:52:46.721Z', 'cernuus', 'Attero utilis iste tabernus commemoro nam.', 'https://foolhardy-jazz.name'),
  (8, 'https://short-term-bid.biz', 'dapifer', 'usque verus coniecto', '_blank', 'Admoveo vesper vestigium tubineus.', 'Y', 8, 8, '2025-12-31T15:09:36.122Z', 'amet', 'Vinculum asperiores vulgo caelum adeptio vacuus absens ad acceptus suggero.', 'https://meaty-pharmacopoeia.info'),
  (9, 'https://yellow-scholarship.net/', 'cornu', 'earum defetiscor timidus', '_self', 'Valens truculenter tonsor bene.', 'Y', 9, 9, '2025-12-31T16:37:21.181Z', 'aggredior', 'Tantum absorbeo traho corrupti amitto ater alias.', 'https://big-going.biz/'),
  (10, 'https://petty-guard.biz/', 'velut', 'congregatio culpa demoror', '_blank', 'Dapifer vitae victoria vereor absque statim esse tam constans celebrer.', 'Y', 10, 10, '2025-12-31T17:59:13.945Z', 'viduo', 'Aestus tenax delectatio.', 'https://elderly-flat.net/');

-- wp_options: 10 rows
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
  (1, 'perferendis', 'A dolorum turbo tonsor.', 'yes'),
  (2, 'carus', 'Debitis iure vomito cerno curvo adipiscor.', 'yes'),
  (3, 'ulciscor', 'Delectus ademptio veritatis ara.', 'yes'),
  (4, 'utor', 'Sortitus vigor vomer verumtamen demulceo soluta desparatus annus.', 'yes'),
  (5, 'contego', 'Patria attollo amor viduo.', 'yes'),
  (6, 'aedificium', 'Commodo temperantia coma maxime aveho volup est repellat accendo.', 'yes'),
  (7, 'validus', 'Tempora despecto corrumpo adsuesco quos attollo ducimus arbitro capitulus beatus.', 'no'),
  (8, 'ago', 'Altus natus suadeo facilis dens tardus cui.', 'yes'),
  (9, 'cumque', 'Voluptatum eaque utique abutor.', 'yes'),
  (10, 'saepe', 'Placeat despecto tero adsidue conturbo ter unus commodi solio.', 'yes');

-- wp_terms: 10 rows
INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
  (1, 'pecco', 'ulterius-minus-tenetur', 1),
  (2, 'aurum', 'creta-tabernus-cumque', 2),
  (3, 'iusto', 'ventus-ait-amoveo', 3),
  (4, 'dolore', 'accusator-vigilo-sopor', 4),
  (5, 'adimpleo', 'desino-caelum-deduco', 5),
  (6, 'soleo', 'vigor-quibusdam-suppono', 6),
  (7, 'delibero', 'tertius-doloremque-succedo', 7),
  (8, 'claustrum', 'tergiversatio-urbs-ulterius', 8),
  (9, 'adeptio', 'defetiscor-carpo-tersus', 9),
  (10, 'velociter', 'aranea-ex-usus', 10);

-- wp_term_taxonomy: 10 rows
INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
  (1, 4, 'category', 'Caritas ultra aliqua caelestis vergo antepono toties adinventitias aeger.', 1, 1),
  (2, 10, 'link_category', 'Ambitus commodo fugiat sono volva natus.', 1, 2),
  (3, 6, 'category', 'Somniculosus acsi tenuis sublime ago sodalitas.', 1, 3),
  (4, 3, 'post_tag', 'Campana viridis cunctatio velum saepe sumo molestiae.', 1, 4),
  (5, 7, 'category', 'Thema nemo soleo validus sollers sui curtus.', 1, 5),
  (6, 3, 'category', 'Aliquam cribro libero.', 1, 6),
  (7, 3, 'link_category', 'Calcar spes voluptate inflammatio angustus.', 1, 7),
  (8, 10, 'category', 'Consequatur cetera cursim adinventitias commodi.', 1, 8),
  (9, 9, 'link_category', 'Tamdiu armarium depulso casso cornu tribuo damno cauda acervus custodia.', 1, 9),
  (10, 5, 'category', 'Coruscus basium vapulus.', 1, 10);

-- wp_term_relationships: 10 rows
INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
  (1, 1, 1),
  (2, 10, 2),
  (3, 5, 3),
  (4, 5, 4),
  (5, 6, 5),
  (6, 1, 6),
  (7, 2, 7),
  (8, 9, 8),
  (9, 9, 9),
  (10, 8, 10);

-- wp_termmeta: 10 rows
INSERT INTO `wp_termmeta` (`meta_id`, `term_id`, `meta_key`, `meta_value`) VALUES
  (1, 5, 'usque', NULL),
  (2, 5, 'vigor', 'Sed utor civis aestus.'),
  (3, 5, 'curis', NULL),
  (4, 10, 'vinitor', 'Curis paens substantia verumtamen admiratio curatio sono vos delego tempore.'),
  (5, 3, 'carpo', 'Solum tam concido rem maiores tricesimus tersus tero tres.'),
  (6, 3, 'architecto', 'Cicuta conforto comitatus virtus.'),
  (7, 5, 'vicinus', 'Vero ad cubicularis.'),
  (8, 5, 'accedo', NULL),
  (9, 2, 'antea', NULL),
  (10, 6, 'culpa', NULL);

-- wp_users: 10 rows
INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
  (1, 'cilicium subseco super', 'EECjwZLvPYUVSNE', 'tabesco deludo cum', 'Russell_Kilback93@yahoo.com', 'https://dutiful-airmail.org/', '2025-04-02T05:27:31.947Z', 'tardus curatio quos', 1, 'Mr. Marty Botsford'),
  (2, 'callide ratione venustas', 'bgTHF_7Su9UOCSm', 'accendo admoneo thermae', 'Karolann.Mohr@yahoo.com', 'https://handy-hamburger.net/', '2025-07-23T21:14:21.624Z', 'sumo creo aeneus', 2, 'Merl Schaefer'),
  (3, 'ratione despecto allatus', '2CY2G8texV4jYTH', 'tego clamo conspergo', 'Alma_Larkin@hotmail.com', 'https://subdued-sushi.biz', '2025-10-01T23:38:53.844Z', 'absconditus adulescens verus', 3, 'Mr. Wallace Ankunding'),
  (4, 'defendo curo absens', 'x2JAvxbsLDjBu3D', 'curtus spiritus civitas', 'Kitty28@yahoo.com', 'https://posh-flood.name', '2025-02-08T19:55:15.739Z', 'atqui cresco aliquam', 4, 'Deborah Romaguera'),
  (5, 'totam termes arbitro', '4Crtrtd9cWtZUOw', 'sublime terra comptus', 'Lempi.Schmidt@gmail.com', 'https://sunny-ghost.name', '2025-03-28T19:54:22.086Z', 'conspergo subnecto venustas', 5, 'Khalil Bins'),
  (6, 'occaecati sed tergo', 'qQLFlnbHqx9m18B', 'coerceo adhuc tribuo', 'Nina.Denesik41@yahoo.com', 'https://kosher-label.com/', '2025-03-21T11:40:42.178Z', 'atqui vespillo nam', 6, 'Alexandra Stark III'),
  (7, 'tricesimus velociter vorago', 'RuwxzAn_MKAyvBQ', 'uxor conduco auctus', 'James.Greenfelder@hotmail.com', 'https://uncomfortable-cow.biz', '2025-01-07T19:24:49.018Z', 'conicio vociferor teneo', 7, 'Hailie Hayes DVM'),
  (8, 'vulgivagus vinitor vobis', 'EmB1IpdvrDzDttF', 'arto derideo cohors', 'Dallas88@hotmail.com', 'https://weekly-chops.net', '2025-12-15T12:05:32.386Z', 'deleo color supellex', 8, 'Lily Kemmer-Harvey'),
  (9, 'cuppedia cuppedia abstergo', 'jHE7RZIsq1HiNry', 'natus expedita caste', 'Mckenna.Mann@yahoo.com', 'https://informal-freight.name', '2025-01-17T18:44:19.252Z', 'vulgo similique deorsum', 9, 'Elvera Donnelly'),
  (10, 'ut cervus vigor', 'GdChqKy4sLmmedb', 'uredo voro voluptatem', 'Vern_Bruen15@yahoo.com', 'https://excellent-cutlet.info', '2025-04-07T11:07:01.837Z', 'deripio tremo subnecto', 10, 'Debbie Lockman');

-- wp_posts: 10 rows
INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
  (1, 9, '2025-12-06T14:24:54.589Z', 1, 'Arbor velit quo amor uxor. Tutamen est accommodo. Colo comburo arceo desolo commodo vehemens cernuus stultus cerno.
Solium pecco alii tendo totus cometes. Ab auxilium adhuc aegrotatio sollers. Spes hic damnatio caput celebrer adhuc umerus.
Solum viduo thema. Ducimus cotidie explicabo centum. Temptatio cunabula solum quisquam verus.', 'Viriliter adhaero caput uberrime eos.', 'Atque sit succurro deficio nemo uredo patrocinor volup coruscus.', 'publish', 'open', 'open', 'AvRXcEXh_TCWs6u', 'delicate-alias-capillus', 'A commodo suppono comitatus talus aeternus aliquam desparatus cogo.', 'Urbanus triduana hic victus uredo supra a deprecator condico quia.', '2025-12-31T17:36:34.071Z', 1, 'Benigne adaugeo volup clementia tui tergo trans deripio caput admoneo.', 1, 'https://unsightly-opera.net/', 1, 'page', 'application', 1),
  (2, 4, '2025-10-26T15:25:32.293Z', 1, 'Officia aliquam quas vomer.', 'Video cura deficio repellendus careo stultus ago.', 'Cohors delibero uter adsidue.', 'pending', 'open', 'open', 'DHi_p5pCvtaq3M3', 'usus-terga-curo', 'Cunae vita accendo tredecim.', 'Turpis statua aurum celebrer cubicularis volaticus.', '2025-12-31T12:05:35.693Z', 1, 'Culpa quidem suspendo patior cimentarius tredecim. Somnus adhaero confero impedit amicitia aestas. Velit tam tenus suggero arguo socius suadeo.
Adeo tamen turpis condico voveo taceo auctor attonbitus. Creator adamo ulciscor sit traho allatus commodo sint cupiditate confero. Voveo maiores possimus quo aduro succurro.
Temptatio tracto cernuus condico volutabrum degusto. Vinco substantia ancilla corrigo acidus. Alveus demergo clamo viduo crapula hic asper.', 1, 'https://babyish-digit.info/', 2, 'post', 'application', 2),
  (3, 10, '2025-10-21T11:56:25.197Z', 1, 'Surculus vindico vobis causa adamo. Ducimus repellendus vulgo arceo consuasor corrigo absorbeo appello. Succedo caterva coadunatio cohibeo auctor.', 'Vulgus cunabula dolore arguo vacuus adnuo nobis.', 'Angelus ad corrupti.', 'pending', 'closed', 'closed', 'q1qpSvmmPeRtNIe', 'vomer-statua-ademptio', 'Cultellus sollicito tricesimus.', 'Utique antiquus provident antiquus sophismata eum suscipit deserunt.', '2025-12-31T08:36:03.478Z', 1, 'Thesaurus tenax harum conculco carus eligendi curia et calculus. Apparatus advenio currus subseco. Audio patria repellendus supplanto combibo fuga vae.', 1, 'https://physical-substitution.info', 3, 'post', 'audio', 3),
  (4, 9, '2025-03-14T13:10:39.121Z', 1, 'Conatus crustulum molestias error tempus audeo quam bonus. Anser vobis defendo combibo.', 'Valetudo alveus campana conturbo aestivus soluta arcesso delectus.', 'Vulticulus arma acerbitas cupiditas utilis pectus acies.', 'publish', 'open', 'open', 'eKY9VyVaiiqEhDu', 'succedo-cura-tenus', 'Pecco ad pecto totidem pax tardus quasi acervus.', 'Dolores torrens supra aspernatur calco conforto causa corona vicinus magni.', '2025-12-31T04:02:41.313Z', 1, 'Colo itaque auditor turba ascit conitor sto adficio.', 1, 'https://quintessential-smog.name', 4, 'page', 'application', 4),
  (5, 6, '2025-11-06T14:08:59.588Z', 1, 'Defleo amplexus excepturi tolero placeat thermae cognomen. Animadverto vox alveus bonus ara. Suus conculco bene commodi convoco alioqui asporto subvenio arca.', 'Abstergo aeternus tonsor cibo optio.', 'Vox sulum terga tantillus vitiosus pecus.', 'publish', 'open', 'closed', 'n9GjinLowsL4CYg', 'necessitatibus-coepi-aegre', 'Earum quibusdam rem clementia aequitas comis adopto turbo subito vestrum.', 'Corpus argumentum cetera cubicularis.', '2025-12-31T22:09:22.299Z', 1, 'Trepide confido attonbitus. Aestivus excepturi ademptio ocer. Iure cattus abutor viscus supellex copia impedit tersus bibo. Charisma corroboro demulceo infit. Tersus coaegresco dolorem decet creo vobis curo candidus thalassinus. Valetudo approbo clamo tabernus sumptus.', 1, 'https://overcooked-object.info/', 5, 'page', 'image', 5),
  (6, 4, '2025-12-31T22:14:01.028Z', 1, 'Basium taedium tener. Alii rerum substantia speciosus aqua casus. Patruus perspiciatis cupiditas hic texo amita.
Amiculum quam curto. Cribro quos dolores custodia autus. Dedecor excepturi torrens.
Cado curiositas abscido. Civitas ipsam aestivus utrimque vigor audio virga voluptatibus amoveo dens. Timor depulso attollo cariosus arbustum credo viscus pax.', 'Paens tersus apostolus viduo villa amplus atque.', 'Tribuo astrum commemoro voluptatibus ipsam.', 'draft', 'open', 'open', '9QRDFLXD1Nb0uSU', 'tam-minus-caterva', 'Crepusculum agnitio bibo.', 'Cupressus clamo tabgo amo bonus.', '2025-12-31T11:54:51.693Z', 1, 'Tergeo suppellex fugit uterque. Ater bestia adinventitias. Tamquam censura virgo tepesco aetas ex vindico soluta synagoga aspernatur.', 1, 'https://warped-surface.net/', 6, 'post', 'image', 6),
  (7, 8, '2025-05-27T11:07:25.684Z', 1, 'Conqueror substantia artificiose corporis demulceo aetas. Statim sortitus terreo qui sortitus speciosus carbo adulatio. Careo usque tabella acer tergiversatio bos amaritudo accommodo quidem.', 'Studio conturbo textilis.', 'Avarus sequi aeternus nemo peior cernuus adversus delectus.', 'draft', 'open', 'closed', 'lXtnuhkVu8gghTW', 'ustulo-conqueror-adinventitias', 'Labore crepusculum sodalitas textus canis colligo cunabula demitto.', 'Suppellex veniam eum vesco valetudo ustilo.', '2025-12-31T22:44:40.323Z', 1, 'Officia charisma vapulus.
Accedo tepesco vinculum.', 1, 'https://angelic-slipper.info', 7, 'page', 'text', 7),
  (8, 4, '2025-07-10T22:42:49.687Z', 1, 'Stabilis vomica similique quas creo peccatus aequitas viscus. Tollo aiunt velut umbra adeptio perspiciatis. Aro tenetur constans abscido. Adfero tui eveniet alter attero. Aliquid subvenio adaugeo facilis totus laboriosam itaque.', 'Celo coerceo venustas thalassinus adfectus conventus arcus.', 'Eaque abutor decretum verus utilis bellicus adulatio viduo doloribus ancilla.', 'draft', 'open', 'closed', 'NcTLBNfLBL5WuxD', 'nam-creptio-statua', 'Ocer dolorem suggero cultellus verumtamen undique.', 'Artificiose subiungo coruscus circumvenio tergo aut.', '2025-12-31T08:15:14.496Z', 1, 'Vindico aspernatur auditor crepusculum. Tibi comminor vinco terror clarus aequitas deinde cupiditate. Acceptus totam beatus.
Statim utilis tenus amitto tibi aufero. Laudantium vacuus auditor utique cura vallum ulterius. Illo civis abeo ulterius cenaculum vorago vetus.
Color fugiat condico aestivus veritatis. Acerbitas solio sum itaque defluo caput cura tempora. Ago texo tendo abutor credo cupio vorax verumtamen careo curriculum.', 1, 'https://windy-thyme.biz/', 8, 'page', 'font', 8),
  (9, 7, '2025-05-06T14:32:23.207Z', 1, 'Crepusculum unde administratio. Decet ab deduco amiculum neque. Conor super aut.
Pectus barba damno sustineo calco. Amoveo est cui degero collum ocer tunc. Denego amitto voluntarius tabesco eaque torqueo agnitio custodia clarus aetas.
Universe abundans curvo antea terror defero sequi repudiandae tam vulariter. Acerbitas carmen tantillus quam alter cito. Ter cariosus comburo voluptatibus adficio verus audacia decretum textilis.', 'Capio molestias deporto consequuntur unus arcesso cupiditas.', 'Baiulus aegrus conspergo subito careo sui atqui valetudo blanditiis curatio.', 'draft', 'open', 'closed', 'OPIsCbl4XLrapHa', 'bibo-conventus-corrupti', 'Voco admoneo summa tempora stabilis decretum adfectus.', 'Ad amaritudo tredecim viscus conturbo abduco.', '2025-12-31T11:31:04.002Z', 1, 'Canis vesco amplitudo stella cuppedia tondeo volaticus angelus callide cuius. Praesentium optio calculus tamen sortitus cimentarius canis taceo crapula. Valeo temperantia desidero perspiciatis ullam tubineus.', 1, 'https://snoopy-academics.org', 9, 'post', 'application', 9),
  (10, 5, '2025-10-23T20:19:42.372Z', 1, 'Sonitus quidem compello textilis pecus casso volup vitium. Traho deripio usus abundans aegre appello fugiat.', 'Vester vomica cunctatio adfero.', 'Casso averto vulnero sodalitas astrum capitulus vesica currus solutio.', 'draft', 'open', 'open', 'NoR_G0HP1MUvXQA', 'iusto-deripio-solium', 'Aperiam aureus trans conor tres curis viscus consequatur.', 'Casus super delectus voluptatum comminor triumphus.', '2025-12-31T17:20:29.795Z', 1, 'Inventore caries pauci temporibus venia uredo dapifer comes adimpleo. Sol adamo cometes aeternus contabesco vomer cupressus vorago coma adsidue. Acquiro deripio coruscus amet. Antepono depromo deprecator ceno perferendis armarium defluo arcesso. Laborum cognomen cerno ater tenetur video eos. Cruciamentum arbor aufero modi defessus nam vacuus deripio aequus commemoro.', 1, 'https://graceful-nightlife.name/', 10, 'page', 'audio', 10);

-- wp_comments: 10 rows
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES
  (1, 7, 'Noelia', 'Clifton74@hotmail.com', 'https://optimistic-cutover.info/', '1af4:a5de:21f9:6364:b4d6:384a:c41f:55e2', '2025-12-31T04:34:19.806Z', 1, 'Clarus stips enim suspendo quisquam acidus comparo correptius.', 1, 'pending', 'Googlebot/2.1 (+http://www.google.com/bot.html)', 'contego', 1, 10),
  (2, 10, 'Reginald', 'Elmira53@gmail.com', 'https://cute-swath.org', '7216:0ca6:efb5:e9ee:d9e3:f9fe:96b7:cd93', '2025-12-31T02:19:14.462Z', 1, 'Provident voluptate calculus confugo.', 2, 'approved', 'Googlebot/2.1 (+http://www.google.com/bot.html)', 'caput', 1, 4),
  (3, 9, 'Dewey', 'Brett72@hotmail.com', 'https://waterlogged-in-joke.biz/', '59.172.158.139', '2025-12-31T01:59:07.218Z', 1, 'Ullus vesper vestrum utrimque cuius complectus asporto thesis.', 3, 'approved', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_15_7) AppleWebKit/593.29.0 (KHTML, like Gecko) Chrome/111.6.15.3 Safari/584.86.42', 'antea', 1, 7),
  (4, 8, 'Laverne', 'Clifton.Bayer@gmail.com', 'https://polished-hope.biz/', '148.169.207.197', '2025-12-31T09:17:02.286Z', 1, 'Deleniti baiulus utroque crastinus.', 4, 'approved', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/119.0', 'optio', 1, 10),
  (5, 9, 'Bobbie', 'Carolyn54@gmail.com', 'https://unused-fundraising.name', '27.62.172.231', '2025-12-31T08:11:49.175Z', 1, 'Vobis amitto arbustum molestias strues bis carcer thorax veniam.', 5, 'approved', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/566.61.50 (KHTML, like Gecko) Version/16.1 Safari/547.95.67', 'patruus', 1, 9),
  (6, 5, 'Anibal', 'Estella.Schaden@yahoo.com', 'https://astonishing-impostor.info', '1ff1:8fda:528f:93fb:ef5f:a4b6:b2c6:cfbe', '2025-12-31T04:49:32.889Z', 1, 'Tempora aut aro aliqua tergiversatio statim amplitudo compello turbo.', 6, 'approved', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_15_7) AppleWebKit/538.77.9 (KHTML, like Gecko) Chrome/113.2.17.3 Safari/589.26.60', 'demitto', 1, 5),
  (7, 6, 'Davion', 'Blake_Connelly43@gmail.com', 'https://ill-responsibility.net', '216.155.154.23', '2025-12-31T02:28:43.629Z', 1, 'Acer carbo atavus.', 7, 'approved', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:118.0) Gecko/20100101 Firefox/133.0', 'decor', 1, 4),
  (8, 10, 'Buddy', 'Vivianne90@gmail.com', 'https://oval-disclosure.biz', 'bd01:be6b:bcaf:7d2e:3e2f:d73f:e8ae:fc48', '2025-12-31T18:13:42.872Z', 1, 'Complectus thalassinus vicissitudo conscendo apparatus pecto.', 8, 'denied', 'Googlebot/2.1 (+http://www.google.com/bot.html)', 'ademptio', 1, 1),
  (9, 9, 'Owen', 'Ida84@yahoo.com', 'https://ruddy-blight.com', '7d93:a7a3:f2fd:74df:00c3:a6eb:cea4:9ccf', '2025-12-31T05:12:52.524Z', 1, 'Vix velit animadverto cimentarius vulgus pauper tibi.', 9, 'approved', 'Mozilla/5.0 (Linux; Android 7; SM-G998N) AppleWebKit/563.81 (KHTML, like Gecko) Chrome/68.4.5.20 Mobile Safari/586.85', 'tristis', 1, 4),
  (10, 3, 'Maudie', 'Alexis.Funk@gmail.com', 'https://altruistic-petal.name/', '1d29:7b4c:88be:ab5a:69f4:aeda:f721:f3d9', '2025-12-31T09:39:46.029Z', 1, 'Cotidie catena conventus defaeco arbustum.', 10, 'approved', 'Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/93.0', 'cauda', 1, 10);

-- wp_commentmeta: 10 rows
INSERT INTO `wp_commentmeta` (`meta_id`, `comment_id`, `meta_key`, `meta_value`) VALUES
  (1, 5, 'aegre', NULL),
  (2, 7, 'sophismata', 'Tertius contigo sequi coaegresco volaticus corrupti decretum surculus.'),
  (3, 4, 'neque', NULL),
  (4, 3, 'verus', 'Maxime creptio civis argumentum turpis minus arcus.'),
  (5, 10, 'terga', 'Vilitas claustrum supplanto vulgus supplanto ademptio arma trepide degusto.'),
  (6, 7, 'desidero', NULL),
  (7, 10, 'cum', 'Speciosus conqueror tener sequi aperte circumvenio.'),
  (8, 5, 'arcesso', 'Succedo templum adiuvo centum aetas denuncio delicate eos adduco.'),
  (9, 6, 'considero', NULL),
  (10, 3, 'rem', 'Antepono vicissitudo amita templum carus abutor.');

-- wp_postmeta: 10 rows
INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
  (1, 7, 'consequatur', NULL),
  (2, 5, 'est', NULL),
  (3, 4, 'cuius', 'Verecundia veritatis coma depopulo.'),
  (4, 1, 'maiores', 'Copiose vos tenuis.'),
  (5, 6, 'demergo', 'Tollo dedico sollicito ultio tamen harum.'),
  (6, 6, 'casso', 'Quam blandior atavus neque.'),
  (7, 10, 'creo', NULL),
  (8, 6, 'vilitas', NULL),
  (9, 2, 'adinventitias', 'Perferendis ambitus aro curiositas utique crebro spoliatio venio appositus.'),
  (10, 8, 'uredo', NULL);

-- wp_usermeta: 10 rows
INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
  (1, 3, 'templum', NULL),
  (2, 1, 'commodi', 'Tonsor thesis volo thymum delinquo vero.'),
  (3, 3, 'templum', NULL),
  (4, 4, 'depereo', NULL),
  (5, 4, 'delinquo', NULL),
  (6, 7, 'cohaero', NULL),
  (7, 8, 'aspicio', 'Vobis comparo delicate sollicito.'),
  (8, 4, 'aut', 'Acsi paulatim charisma iusto soluta admoneo aestivus vesper.'),
  (9, 3, 'theca', NULL),
  (10, 2, 'cursim', 'Vulgus aliqua thesis dedecor acquiro ater vacuus caveo.');

COMMIT;
