-- ============================================================
-- WordPress CMS Schema — MySQL (authentic WordPress DDL)
-- Covers: BIGINT UNSIGNED, LONGTEXT, VARCHAR utf8mb4, TINYINT(1),
-- KEY shorthand, FULLTEXT KEY, UNIQUE KEY, key-value meta tables,
-- ON DELETE CASCADE, DATETIME DEFAULT, text collation.
-- ============================================================

-- WordPress stores all its data in a single database with a
-- configurable prefix (default: wp_). This is the real schema
-- as generated by WordPress 6.x.

CREATE TABLE `wp_users` (
  `ID`                  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_login`          VARCHAR(60)  NOT NULL DEFAULT '',
  `user_pass`           VARCHAR(255) NOT NULL DEFAULT '',
  `user_nicename`       VARCHAR(50)  NOT NULL DEFAULT '',
  `user_email`          VARCHAR(100) NOT NULL DEFAULT '',
  `user_url`            VARCHAR(100) NOT NULL DEFAULT '',
  `user_registered`     DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_activation_key` VARCHAR(255) NOT NULL DEFAULT '',
  `user_status`         INT(11)      NOT NULL DEFAULT 0,
  `display_name`        VARCHAR(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `user_login_key`  (`user_login`),
  KEY `user_nicename`   (`user_nicename`),
  KEY `user_email`      (`user_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_usermeta` (
  `umeta_id`  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`   BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `meta_key`  VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`umeta_id`),
  KEY `user_id`  (`user_id`),
  KEY `meta_key` (`meta_key`(191)),
  FOREIGN KEY (`user_id`) REFERENCES `wp_users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_posts` (
  `ID`                    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_author`           BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `post_date`             DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt`         DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content`          LONGTEXT     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_title`            TEXT         CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_excerpt`          TEXT         CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_status`           VARCHAR(20)  NOT NULL DEFAULT 'publish',
  `comment_status`        VARCHAR(20)  NOT NULL DEFAULT 'open',
  `ping_status`           VARCHAR(20)  NOT NULL DEFAULT 'open',
  `post_password`         VARCHAR(255) NOT NULL DEFAULT '',
  `post_name`             VARCHAR(200) NOT NULL DEFAULT '',
  `to_ping`               TEXT         CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `pinged`                TEXT         CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_modified`         DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt`     DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` LONGTEXT     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_parent`           BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `guid`                  VARCHAR(255) NOT NULL DEFAULT '',
  `menu_order`            INT(11)      NOT NULL DEFAULT 0,
  `post_type`             VARCHAR(20)  NOT NULL DEFAULT 'post',
  `post_mime_type`        VARCHAR(100) NOT NULL DEFAULT '',
  `comment_count`         BIGINT(20)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `post_name`         (`post_name`(191)),
  KEY `type_status_date`  (`post_type`, `post_status`, `post_date`, `ID`),
  KEY `post_parent`       (`post_parent`),
  KEY `post_author`       (`post_author`),
  FULLTEXT KEY `post_search` (`post_title`, `post_content`, `post_excerpt`),
  FOREIGN KEY (`post_author`) REFERENCES `wp_users` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_postmeta` (
  `meta_id`    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_id`    BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `meta_key`   VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`meta_id`),
  KEY `post_id`  (`post_id`),
  KEY `meta_key` (`meta_key`(191)),
  FOREIGN KEY (`post_id`) REFERENCES `wp_posts` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_terms` (
  `term_id`    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`       VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `slug`       VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL DEFAULT '',
  `term_group` BIGINT(10)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`term_id`),
  KEY `slug`       (`slug`(191)),
  KEY `name`       (`name`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_term_taxonomy` (
  `term_taxonomy_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_id`          BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `taxonomy`         VARCHAR(32)  NOT NULL DEFAULT '',
  `description`      LONGTEXT     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent`           BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `count`            BIGINT(20)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`term_taxonomy_id`),
  UNIQUE KEY `term_id_taxonomy` (`term_id`, `taxonomy`),
  KEY `taxonomy`     (`taxonomy`),
  FOREIGN KEY (`term_id`) REFERENCES `wp_terms` (`term_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_term_relationships` (
  `object_id`        BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `term_taxonomy_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `term_order`       INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`object_id`, `term_taxonomy_id`),
  KEY `term_taxonomy_id` (`term_taxonomy_id`),
  FOREIGN KEY (`term_taxonomy_id`) REFERENCES `wp_term_taxonomy` (`term_taxonomy_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_termmeta` (
  `meta_id`    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_id`    BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `meta_key`   VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`meta_id`),
  KEY `term_id`  (`term_id`),
  KEY `meta_key` (`meta_key`(191)),
  FOREIGN KEY (`term_id`) REFERENCES `wp_terms` (`term_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_options` (
  `option_id`    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `option_name`  VARCHAR(191) NOT NULL DEFAULT '',
  `option_value` LONGTEXT     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `autoload`     VARCHAR(20)  NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`option_id`),
  UNIQUE KEY `option_name` (`option_name`),
  KEY `autoload`           (`autoload`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_comments` (
  `comment_ID`          BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_post_ID`     BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `comment_author`      TINYTEXT   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment_author_email` VARCHAR(100) NOT NULL DEFAULT '',
  `comment_author_url`  VARCHAR(200) NOT NULL DEFAULT '',
  `comment_author_IP`   VARCHAR(100) NOT NULL DEFAULT '',
  `comment_date`        DATETIME    NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt`    DATETIME    NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content`     TEXT        CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment_karma`       INT(11)     NOT NULL DEFAULT 0,
  `comment_approved`    VARCHAR(20) NOT NULL DEFAULT '1',
  `comment_agent`       VARCHAR(255) NOT NULL DEFAULT '',
  `comment_type`        VARCHAR(20) NOT NULL DEFAULT 'comment',
  `comment_parent`      BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `user_id`             BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID`              (`comment_post_ID`),
  KEY `comment_approved_date_gmt`    (`comment_approved`, `comment_date_gmt`),
  KEY `comment_date_gmt`             (`comment_date_gmt`),
  KEY `comment_parent`               (`comment_parent`),
  KEY `comment_author_email`         (`comment_author_email`(10)),
  FULLTEXT KEY `comment_search`      (`comment_content`),
  FOREIGN KEY (`comment_post_ID`) REFERENCES `wp_posts` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_commentmeta` (
  `meta_id`    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `meta_key`   VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`meta_id`),
  KEY `comment_id` (`comment_id`),
  KEY `meta_key`   (`meta_key`(191)),
  FOREIGN KEY (`comment_id`) REFERENCES `wp_comments` (`comment_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wp_links` (
  `link_id`          BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `link_url`         VARCHAR(255) NOT NULL DEFAULT '',
  `link_name`        VARCHAR(255) NOT NULL DEFAULT '',
  `link_image`       VARCHAR(255) NOT NULL DEFAULT '',
  `link_target`      VARCHAR(25)  NOT NULL DEFAULT '',
  `link_description` VARCHAR(255) NOT NULL DEFAULT '',
  `link_visible`     VARCHAR(20)  NOT NULL DEFAULT 'Y',
  `link_owner`       BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
  `link_rating`      INT(11)      NOT NULL DEFAULT 0,
  `link_updated`     DATETIME     NOT NULL DEFAULT '0000-00-00 00:00:00',
  `link_rel`         VARCHAR(255) NOT NULL DEFAULT '',
  `link_notes`       MEDIUMTEXT   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `link_rss`         VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`link_id`),
  KEY `link_visible` (`link_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
